### ISSUE TITLE
PhoneNumber vs Phonenumber??

### ISSUE THREAD

**Issue by mauricio-morales** [twcclegg/libphonenumber-csharp#10]
In `Phonenumber.cs`, the protobuff defined 2 classes with _virtually_ the same name except for casing. 

```
  public static partial class Phonenumber
```

```
  public partial class PhoneNumber
```

This is preventing me from using the _libphonenumber-csharp_ library in a VB.NET project (VB.NET being case insensitive, throws the error `error BC30560: 'PhoneNumber' is ambiguous in the namespace 'PhoneNumbers'.`).

I could fix and build the reference myself, but would love to be able to use the Nuget package instead. Think this is something you'd consider fixing? (I'll see if I can carve some time tomorrow to fix it on my own and submit a PR).

**Comment by aidanbebbington** [comment]
Thanks again for doing this!  Sorry it took me so long
