### ISSUE TITLE
Dutch 097 numbers not recognized

### ISSUE THREAD

**Issue by tsagld** [twcclegg/libphonenumber-csharp#101]
Since 2017, Dutch providers have to provide 097- numbers as mobile numbers.
The library does not recognize these numbers. 
A full internationalized number looks like this +3197nnnnnnnnn. The 97 is followed by 9 digits.
More information here: https://www.kpn.com/zakelijk/service/mobiel/nummerwissel.htm

**Comment by twcclegg** [comment]
Please see https://github.com/twcclegg/libphonenumber-csharp/blob/master/CONTRIBUTING.md
Something like http://libphonenumber.appspot.com/phonenumberparser?number=%2B3197123456789 shows up as TOO_LONG.
