### ISSUE TITLE
Australian phone numbers starting with 048 not recognised as valid

### ISSUE THREAD

**Issue by stglushchenko** [twcclegg/libphonenumber-csharp#104]
Thank you for the great work! 
I've noticed the previous similar issue with 0460 and checked 048 with [google library test util](http://libphonenumber.appspot.com/phonenumberparser?number=%2B61480000000&country=AU) where` isValidNumber() == true`, but the library returns false from `PhonenNumberUtil.IsValidNumber()`. Will this library be updated anytime soon?

**Comment by twcclegg** [comment]
```c#
        [Fact]
        public void TestAU()
        {
            Assert.True(phoneUtil.IsValidNumber(phoneUtil.Parse("+61460000000", null)));
            Assert.True(phoneUtil.IsValidNumber(phoneUtil.Parse("+61480000000", null)));
        }
```
Passes for me locally are you sure you are using the latest version, 8.10.13, of the library?

**Comment by stglushchenko** [comment]
You're right, Ironically, I've updated the library to the latest version in all the projects of the solution except for unit tests project. Now everything works. Thanks and sorry for bothering without the reason.
