### ISSUE TITLE
IsPossibleNumber implementation is out of sync with upstream

### ISSUE THREAD

**Issue by tomasaschan** [twcclegg/libphonenumber-csharp#105]
It seems that this code
https://github.com/twcclegg/libphonenumber-csharp/blob/39235e984d5d120bfa7fcc3e28f85bf31faff2ba/csharp/PhoneNumbers/PhoneNumberUtil.cs#L2297-L2300
was ported from this
https://github.com/twcclegg/libphonenumber-csharp/blob/39235e984d5d120bfa7fcc3e28f85bf31faff2ba/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2385-L2387
but upstream has changed:
https://github.com/google/libphonenumber/blob/d0d7677a699fd8e7bfdcf82f4a2bfb947efe8c05/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2485-L2489

This is causing us some headache, because we have a Java and a C# application talking to each-other, and were under the assumption that the latest versions of these two libraries would mean we used the same validation rules. Apparently not :)

I'd file a PR for the fix (fixing the C# code is fairly trivial), but I didn't really understand what other steps would be required to pull changes in from upstream correctly.

**Comment by twcclegg** [comment]
This should be fixed in v8.10.14 let me know if it doesn't now behave as expected.
