### ISSUE TITLE
Letters in number are not recognized and no exception is thrown.

### ISSUE THREAD

**Issue by bejto** [twcclegg/libphonenumber-csharp#109]
Hello,

While I was testing this Lib, I noticed that if I enter a letter combination that starts with a valid phone number area code, then this is accepted and the letters are replaced by numbers.
![image](https://user-images.githubusercontent.com/9606944/66650324-a443c180-ec30-11e9-97cc-049f2b2f8549.png)

Greetings
Bejto

**Comment by AwsomeCode** [comment]
@bejto This is just port of https://github.com/googlei18n/libphonenumber
Kindly post your request over there.

**Comment by twcclegg** [comment]
I'm not quite sure what you are expecting to happen but as stated above this port aims to replicate the behavior of the Java version so any changes would need to first be made in the upstream. I've confirmed that the e164 output from the C# version for your input matches what's shown in your screenshot above.
