### ISSUE TITLE
Australian phone number beginning with 0480 not recognised as valid

### ISSUE THREAD

**Issue by ghost** [twcclegg/libphonenumber-csharp#112]
Even though I see numbers starting with 0480 valid here; http://libphonenumber.appspot.com/phonenumberparser?number=%2B61480231902  
the lib returns me invalid.

Is there any chance to fix that ?

Thanks,
Belma

**Comment by twcclegg** [comment]
https://dotnetfiddle.net/TRCAFw is returning true for me, are you using the latest version or can you provide a example?

**Comment by ghost** [comment]
Hi, twcclegg, yes updating the version solved my issue. Thanks a lot ! 👍
