### ISSUE TITLE
Some New Zealand Mobile Numbers Failing

### ISSUE THREAD

**Issue by stevedowling** [twcclegg/libphonenumber-csharp#113]
Looks like NZ has increased the length of some of their mobile numbers (https://www.tnzi.com/numbering-plan) and we are noticing a few +6427 numbers come through that fail validation - +642712345678 would fail, for example. Can you take a look, please?

**Comment by stevedowling** [comment]
Looks like +6429 has the same problem but the others are fine: https://dotnetfiddle.net/ms34w6

**Comment by twcclegg** [comment]
Results seem to match https://libphonenumber.appspot.com/phonenumberparser?number=%2B642712345678. You can open an issue here https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue

**Comment by stevedowling** [comment]
Ok, thanks. I've raised an issue with Google. Will put a hack in place until they have taken a look. 
Cheers.

**Comment by Mitchies1970** [comment]
Just wanted to follow up on above - seems like this latest release still does not validate NZ numbers when 8 digits follow the 7 as in +642712345678 (which this library invalidates) vs + 64271234567 (which this library validates as ok). 
Please bear in mind that according to official specification here - https://www.tnzi.com/numbering-plan - it says that there can be 8 digits after the 27 (the 2 digit code). See below screen shot. 
I will follow up on Google too. 
Thanks.

**Comment by stevedowling** [comment]
Just tested the 8.12.1 release and can confirm that it fixes these number ranges.
