### ISSUE TITLE
Iranian phone number beginning with 905 and 922 not recognised as valid

### ISSUE THREAD

**Issue by Mariaabpr** [twcclegg/libphonenumber-csharp#114]
Iranian phone number beginning with 905 and 922 not recognised as valid
Is there any chance to fix that ?

Thanks,
maria

**Comment by Mariaabpr** [comment]
Example:
989221234567
989051234567

**Comment by AwsomeCode** [comment]
Error type: INVALID_COUNTRY_CODE. Missing or invalid default region. https://libphonenumber.appspot.com/phonenumberparser?number=989221234567.
 You can open an issue here https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue

**Comment by twcclegg** [comment]
They seem like they're valid to me. They need to either be in e164 format or have region provided. https://dotnetfiddle.net/t12baO

**Comment by Mariaabpr** [comment]
this answer helped me a lot. thanks a lot
