### ISSUE TITLE
Returning FIXED_LINE_OR_MOBILE  instead of MOBILE

### ISSUE THREAD

**Issue by cissemy** [twcclegg/libphonenumber-csharp#115]
Hi,
 var numberType = phoneNumberUtil.GetNumberType(phoneNumber) does not return mobile for US mobile phone.
Only getting FIXED_LINE_OR_MOBILE
Thanks

**Comment by twcclegg** [comment]
See https://github.com/google/libphonenumber/blob/master/FAQ.md#why-did-i-get-fixed_line_or_mobile-as-the-type-of-my-phone-number or more explicitly https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L406. Also see `GEO_MOBILE_COUNTRIES` within that file for more details.
