### ISSUE TITLE
How to validate number without throwing exception?

### ISSUE THREAD

**Issue by xperiandri** [twcclegg/libphonenumber-csharp#116]
I found `Parse` that throws the `NumberParseException`. Any other option without exception?

**Comment by twcclegg** [comment]
There is not, this port tries to be as close as it can be to Google's Java version. While I'm not a Java developer it doesn't appear that the TryParse pattern is used much there.
You of course could make your wrapper to do mimic such behavior.

**Comment by mqudsi** [comment]
If it helps, the closest I could get, with the intention of minimizing exceptions thrown for performance reasons (so not just sticking it all in a `try..catch` block):

```csharp
var instance = PhoneNumberUtil.GetInstance();
if (PhoneNumberUtil.IsViablePhoneNumber(normalized)
    && instance.FindNumbers(normalized, "US").Any())
{
    try
    {
        instance.ParseAndKeepRawInput(value ?? "", "US", number);
    }
    catch { }
}
```

**Comment by twcclegg** [comment]
Only addition to this is you generally want to save phoneNumberUtil and not call GetInstance() all the time, that involves acquiring a lock and such. Also the very first call to Parse after loading takes >> than subsequent uses so if there is a use case that it is critical path it is ideal to warm it up first.
