### ISSUE TITLE
Some phone calling codes may not be completely correct

### ISSUE THREAD

**Issue by jomicobasi** [twcclegg/libphonenumber-csharp#118]
Hey,

I'm raising a possible issue about some Regions, for instance, that belong to the USA. Those regions, like American Samoa (AS), have a **prefix** calling code of USA (+1) and some other digits (+1684 is the calling code in case of American Samoa). There are others like this for the USA case. I got into this when I checked [here](https://countrycode.org/). 

Is this possible to resolve in some way?

Thank you!

**Comment by twcclegg** [comment]
Is this a behavior that differs from Google libphonenumber (demo [here](https://libphonenumber.appspot.com/))? If so you can open an issue with them, if not please let me know with an example of differing behavior.

**Comment by jomicobasi** [comment]
Sorry for the hassle. I misunderstood the meaning of Area Code. You can close this issue.
