### ISSUE TITLE
Adding static implicit operator for string conversion

### ISSUE THREAD

**Issue by lilstar132** [twcclegg/libphonenumber-csharp#123]
Adding a `static implicit operator` method for this library would be awesome. For instance:

instead of this:
`var phoneNumber = phoneNumberUtil.Parse(e164PhoneNumber, null);`
using this:
`PhoneNumber phoneNumber = "+393334455667"`

A roughly coded idea would be like this:
(inside PhoneNumbers.PhoneNumber class)
```
public static implicit operator PhoneNumber(string phoneNumber)
{
    return PhoneNumberUtil.GetInstance().Parse(phoneNumber, null);
}
```

**Comment by twcclegg** [comment]
This seems like it would encourage going against best practices, e.g. it is best to obtain phoneNumberUtil once and not call GetInstance() over and over, and also doesn't allow for parsing with region code.
