### ISSUE TITLE
Can not resolve reference: System.Collections.Immutable

### ISSUE THREAD

**Issue by Yahya0007** [twcclegg/libphonenumber-csharp#124]
Hi

I am getting below error in my Xamarin Forms solution;

Can not resolve reference: System.Collections.Immutable, referenced by PhoneNumbers. Please add a NuGet package or assembly reference for System.Collections.Immutable, or remove the reference to PhoneNumbers. StaffApp.Android

It looks like reference to System.Collections.Immutable is present in project StaffApp.Android.

What could be the problem? Xamarin Forms project are net Standard 2 while the some additional projects in solution are net Framework 4.8.

Thanks

Regards

**Comment by twcclegg** [comment]
What version of System.Collections.Immutable are you are you referencing? I did notice that the version referenced by the library is out of date, that will be updated in the next release, you can try it out now using: 
 https://ci.appveyor.com/api/buildjobs/q9683qkfus5my3c4/artifacts/csharp%2FPhoneNumbers%2Fbin%2FRelease%2Flibphonenumber-csharp.8.12.13-63cbe92.nupkg
If that doesn't work can you potentially provide your csproj file contents?
