### ISSUE TITLE
IsViablePhoneNumber returns false for internationl numbers with leading spaces

### ISSUE THREAD

**Issue by kentcb** [twcclegg/libphonenumber-csharp#127]
LINQPad script:

```
var workingInput = "+61466123321";
var failingInput = " " + workingInput;

var isViable1 = PhoneNumberUtil.IsViablePhoneNumber(workingInput);
var isViable2 = PhoneNumberUtil.IsViablePhoneNumber(failingInput);

isViable1.Dump();
isViable2.Dump();
```

Output:

```
True
False
```

**Comment by twcclegg** [comment]
I don't currently have a good setup to test the Java version to see its behavior however you shouldn't be calling `IsViablePhoneNumber` see https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L753 which is marked `@VisibleForTesting` I don't want to introduce a breaking change without a major version bump but if Google revs to 9.x I plan to move everything with that annotation to `internal`.
What is your use case? You probably should be using `phoneUtil.IsPossibleNumber` or `phoneUtil.IsValidNumber`, the viable method just runs the string through a regex to see if it looks kinda like a phone number.
