### ISSUE TITLE
NuGet for .NET Standard support

### ISSUE THREAD

**Issue by nealculiner** [twcclegg/libphonenumber-csharp#13]
Hello,

I tried updating a PCL project to .NET standard after removing this package and then tried reinstalling this package from nuget after changing to .NET standard.  This package will not install for some reason.  FYI

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Thank you for this package by the way!!!

**Comment by aidanbebbington** [comment]
Hi - I'm afraid I've left .NET somewhat, so I'm a bit out of date now.  Do you get a specific error message?

**Comment by nealculiner** [comment]
I created a new class library for .NET core (same as .net standard) and the error is shown below. 

GET https://api.nuget.org/v3-flatcontainer/libphonenumber-csharp/7.5.1/libphonenumber-csharp.7.5.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/libphonenumber-csharp/7.5.1/libphonenumber-csharp.7.5.1.nupkg 296ms
Installing libphonenumber-csharp 7.5.1.
Installing NuGet package libphonenumber-csharp.7.5.1.
Successfully installed 'libphonenumber-csharp 7.5.1' to ClassLibrary1
========== Finished ==========
PATH=.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "D:\Dev\ClassLibrary1.vs\restore.dg"
log  : Restoring packages for D:\Dev\ClassLibrary1\src\ClassLibrary1\project.json...
error: Package libphonenumber-csharp 7.5.1 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package libphonenumber-csharp 7.5.1 supports: net (.NETFramework,Version=v0.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.5.
info : Committing restore...
log  : Writing lock file to disk. Path: D:\Dev\ClassLibrary1\src\ClassLibrary1\project.lock.json
log  : D:\Dev\ClassLibrary1\src\ClassLibrary1\ClassLibrary1.xproj
log  : Restore failed in 374ms.
Errors in D:\Dev\ClassLibrary1\src\ClassLibrary1\ClassLibrary1.xproj
    Package libphonenumber-csharp 7.5.1 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package libphonenumber-csharp 7.5.1 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETStandard,Version=v1.5.
NuGet Config files used:
    C:\Users\Neal\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

**Comment by FanMix** [comment]
Do you plan to support .NET Core? If yes, when ?

**Comment by aidanbebbington** [comment]
That should surely be the plan I guess.  I'm afraid I'm a bit out of date on the .NET front these days.  Would be happy to take a pull request though.

**Comment by RichiCoder1** [comment]
Looks like the merge for .Net Standard went fine, but the actual package does call out .Net Standard support?

**Comment by aidanbebbington** [comment]
What do you mean call out? Is there a standard way of doing that in the
budget package? I'm afraid I'm a bit out of touch these days. I'll Google
it when I get a sec, but if you know a good resource that'd be awesome.

**Comment by RichiCoder1** [comment]
@aidanbebbington Actually, it looks like the appropriate properties are set in the csproj. It's just that your CI is using an *ancient* version of nuget. I'd recommend updating nuget, or wholesale switching to `dotnet pack` if that's possible.

Edit: Relevant Links:
* https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/creating-nuget-packages
* https://docs.microsoft.com/en-us/dotnet/articles/core/tools/csproj

**Comment by brunoblank** [comment]
Any update on this? 

Thanks

**Comment by soroshsabz** [comment]
ITNOA

I think xproj dose not necessary if you are using VS2017.

**Comment by twcclegg** [comment]
Any update to this? Building from source it works just great for netstandard however only net45 is packed in the nupkg.

**Comment by pdpurcell** [comment]
Hey @aidanbebbington,
After reading the comments from @RichiCoder1 and @twcclegg I repackaged a new NuGet version (8.3.1.2).  If you want to publish it then it will provide support for both net45 and netstandard1.0: [PhoneNumbers.8.3.1.2.zip](https://github.com/aidanbebbington/libphonenumber-csharp/files/1091620/PhoneNumbers.8.3.1.2.zip).

**Comment by twcclegg** [comment]
Thanks @pdpurcell. Hoping this can be made available via NuGet soon, it would be much appreciated.

**Comment by aidanbebbington** [comment]
Thanks everyone, I've uploaded pdpurcell's nuget build.  I'd also be happy
to grant access to the nuget package and github to anyone less hopeless
than myself and willing to update this thing from time to time.

**Comment by twcclegg** [comment]
@aidanbebbington If your offer still stands, I'm willing to help maintain this. https://github.com/aidanbebbington/libphonenumber-csharp/pull/29 brings things generally up to date.

**Comment by twcclegg** [comment]
Fixed in 8.3.1.2 and later.
