### ISSUE TITLE
Case of Italy leading zero is not properly handled

### ISSUE THREAD

**Issue by A1rwav3** [twcclegg/libphonenumber-csharp#130]
When a italian number is parsed with the following code:
`PhoneNumber phone = phoneNumberUtil.Parse("0212454875", "IT");`
returns a RegionalNumber property with the leading zero removed (212454875)
The flag HasItalianLeadingZerois correct but the zero is still removed.
The 0 should be kept for RegionalNumber, as it is stated in wikipedia since 1998.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy

**Comment by twcclegg** [comment]
"RegionalNumber"? you mean [`ulong NationalNumber`](https://github.com/twcclegg/libphonenumber-csharp/blob/master/csharp/PhoneNumbers/Phonenumber.cs#L45). All of those properties should not be accessed directly and may become private in the next major release.
I believe you want something like ```C#
phoneNumberUtil.Format(phone, PhoneNumberFormat.NATIONAL)```
which returns `02 1245 4875`

**Comment by A1rwav3** [comment]
You are right, I was talking about NationalNumber. My problem is that the format method returns a value with spaces. What do you advise?

**Comment by twcclegg** [comment]
There's a handful of ways to do that, perhaps the simplest would be 
```C#
util.FormatByPattern(number, PhoneNumberFormat.NATIONAL, new List<NumberFormat>());
```

**Comment by A1rwav3** [comment]
Ok I've tried the last one and it's working as I want. Thank you for your help.
