### ISSUE TITLE
French IoT 15-digit phone numbers

### ISSUE THREAD

**Issue by RedaAouad** [twcclegg/libphonenumber-csharp#131]
Hi,

France decided in 2017 to move from 11 to 15 digit numbers for IoT.
Here's the article: https://www.orange-business.com/en/numbering-iot-sim-move-15-digits

The below example has 2 issues:
```
var nb = instance.Parse("+337000001573827", "FR");

// Issue #1: this returns false
instance.IsValid(nb); 

// Issue #2: this returns '7000001573827' without the leading 0
instance.Format(nb, PhoneNumberFormat.NATIONAL);
```

Could you please handle this format?

**Comment by RedaAouad** [comment]
I have just opened a case here too:
https://issuetracker.google.com/issues/181036937

Are you dependent from them fixing it or could you fix it in this lib meanwhile?

**Comment by RedaAouad** [comment]
And thank you for taking the time to look into it :)

**Comment by twcclegg** [comment]
Unfortunately this library is completely dependent on the metadata from Google. Unfortunately the Google issue appears it was rejected (no IoT support). Given that I don't think there is much that I can do.

**Comment by RedaAouad** [comment]
I understand now that this library fully depends on Google's metadata, so I should file such issues there and won't bother you with them anymore. Thank you for your support.
