### ISSUE TITLE
Formatting an invalid number

### ISSUE THREAD

**Issue by RedaAouad** [twcclegg/libphonenumber-csharp#132]
Hi,

Related to #131, why is the leading 0 removed from a parsed number when the parsing is invalid?

```
var nb1 = instance.Parse("+330611223344", "FR");

// Returns true
instance.IsValid(nb1);

// Correctly returns '06 11 22 33 44'
instance.Format(nb1,  PhoneNumberFormat.NATIONAL);

--------

var nb2 = instance.Parse("+3307000001573827", "FR");

// Returns false
instance.IsValid(nb2);

// Returns '7000001573827', missing the leading 0
instance.Format(nb2,  PhoneNumberFormat.NATIONAL);
```

Is this intentional or a side effect of parsing an invalid number? Could that change to return the leading 0?

Thanks
Reda

**Comment by twcclegg** [comment]
There isn't any attempt to "properly" display invalid numbers given that there is no pattern that describes how it would be formatted. The intention is match the Google behavior [here](https://libphonenumber.appspot.com/phonenumberparser?number=%2B3307000001573827).
