### ISSUE TITLE
Some phone number return wrong results for CN

### ISSUE THREAD

**Issue by steel1041** [twcclegg/libphonenumber-csharp#133]
var rawNumber = "3910998887";
            var countryCode = "CN";
            var n = PhoneUtil.ParseAndKeepRawInput(rawNumber, countryCode);
            Assert.IsTrue(PhoneUtil.IsValidNumberForRegion(n, countryCode));    //should return false
            Assert.IsTrue(PhoneUtil.IsValidNumber(n));                                           //should retun false
            
            CN (China) phone numbers are 11 length and start by 1.

**Comment by twcclegg** [comment]
The behavior above appears to match https://libphonenumber.appspot.com/phonenumberparser?number=3910998887&country=CN you should submit your issue to https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue this library consumes their phone number metadata.
