### ISSUE TITLE
Issue in verifying some Zimbabwe Econet phone numbers

### ISSUE THREAD

**Issue by RMordvinov** [twcclegg/libphonenumber-csharp#134]
This operator has numbers starting with +263 77... or +263 78...
We have numbers that after 78 have 0, i.e. start with +263 780 ... and the utility considers such numbers invalid.
Could you fix it, please?

**Comment by twcclegg** [comment]
Can the issue be reproduced here: https://libphonenumber.appspot.com/? If so please file an issue with Google https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md I don't control the metadata.

**Comment by RMordvinov** [comment]
Yes, it's reproduced.
Got it, thank you very much. Sorry to disturb you.
