### ISSUE TITLE
MAX_LENGTH_FOR_NSN difference

### ISSUE THREAD

**Issue by RobThree** [twcclegg/libphonenumber-csharp#135]
Just curious; is there a reason why `MAX_LENGTH_FOR_NSN` is [defined as 16](https://github.com/twcclegg/libphonenumber-csharp/blob/1b7ff131ab8c3843aa1ccf738992642c4262e8f7/csharp/PhoneNumbers/PhoneNumberUtil.cs#L51) while [it's 17 in Google's code](https://github.com/google/libphonenumber/blob/c6277266fba8223cfc610cfb1e999deb9f876d65/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L64)? It has been 17 [since Dec 3, 2014](https://github.com/google/libphonenumber/commit/5891032ffb4aa574bdff021bf5709f42547db715#diff-90f3e64e59b9360631a6257cf61616529fad0ffa2e396ce58a0a22811ac81c2e) if I'm not mistaken.

**Comment by twcclegg** [comment]
It looks like it was updated from 15 to 16 in 2011 [here](https://github.com/twcclegg/libphonenumber-csharp/commit/984d967a55719c82f1a536ca95335c3999915711) but not updated since. Good catch it'll be fixed in the next release.

**Comment by RobThree** [comment]
Awesome! Thanks!
