### ISSUE TITLE
Continued .net35 support?

### ISSUE THREAD

**Issue by twcclegg** [twcclegg/libphonenumber-csharp#138]
As new version of dotnet are released, supporting them makes supporting them and legacy version concurrently increasingly difficult.
Are people still using the net framework 3.5 version of this library? @neuroid @MichaelEdk @athoik
AppVeyor build image 'Visual Studio 2019' does not have `Microsoft\Portable\v3.5\` https://ci.appveyor.com/project/twcclegg/libphonenumber-csharp/builds/39628489

**Comment by MichaelEdk** [comment]
All good with me if you stop supporting .NET 3.5 in future versions. Thanks for the heads up

**Comment by athoik** [comment]
It's fine stopping support for .NET 3.5 too. 

Thanks for continuing support in modern frameworks!

**Comment by neuroid** [comment]
No objections here 👍
