### ISSUE TITLE
Library not handling 11 digit NL phone numbers

### ISSUE THREAD

**Issue by psaikaushik** [twcclegg/libphonenumber-csharp#139]
We were trying to send some messages using a 11 digit Netherlands phone number which is valid https://www.acm.nl/en/publications/information-about-dutch-097-numbers-non-dutch-providers  but the library says that they are invalid.

**Comment by twcclegg** [comment]
Is the issue present in the Google demo app https://libphonenumber.appspot.com/ if so please file the issue with them, this library intends to match their behavior regardless of their "correctness".
https://github.com/twcclegg/libphonenumber-csharp/blob/master/CONTRIBUTING.md

**Comment by psaikaushik** [comment]
The issue is present with the google library itself.
