### ISSUE TITLE
Required to update US phone number code 627

### ISSUE THREAD

**Issue by nandakumargollu** [twcclegg/libphonenumber-csharp#143]
Required to update US phone number code 627 belongs to Santa Rosa, California

**Comment by twcclegg** [comment]
All metadata [issues](https://github.com/twcclegg/libphonenumber-csharp/blob/master/CONTRIBUTING.md) should be reported to [Google](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) unless behavior is different from https://libphonenumber.appspot.com/
