### ISSUE TITLE
Outdated Version. Next Update?

### ISSUE THREAD

**Issue by Damian1592** [twcclegg/libphonenumber-csharp#149]
Hi Tom
This library is currently a bit behind the [libphonenumber](https://github.com/google/libphonenumber)-project.
Is there any time frame when we can expect the newest port to C#?
I currently have issues with outdated region codes for the Central African Republic.

Thanks for your awesome work. This C# port is very useful for our project!

Best Regards
Damian

**Comment by twcclegg** [comment]
Sorry things have been a bit busy for me as of late. All the metadata should be up to date now.

**Comment by Damian1592** [comment]
Hi Tom

Thank you very much for the quick update!
It works as intended and my CF-phone-number is now recognized as valid.
Keep up the good work!

Best regards
Damian
