### ISSUE TITLE
Missing phone numbers as regex are not including them

### ISSUE THREAD

**Issue by JL-Ikosoft** [twcclegg/libphonenumber-csharp#151]
Hi :)

Thanks for your work!

In France there's 5 regions for fixed lines. 
![image](https://user-images.githubusercontent.com/93907249/164034133-637fd335-f6d5-46d9-bca7-11eba36c0ef0.png)

Seems thet regular expression is not including region South East which has 04 as prefix `(?:[1-35]\d|4[1-9])\d{7}`
![image](https://user-images.githubusercontent.com/93907249/164033487-fb0051fb-a4de-4d02-b3e6-3079cffc2db4.png)

Same for mobile phones as we have numbers starting with 07: `(?:6(?:[0-24-8]\d|3[0-8]|9[589])|7(?:00|[3-9]\d))\d{6}`
![image](https://user-images.githubusercontent.com/93907249/164033761-9062481a-8723-4954-9627-f5f84c32d8e3.png)

How can we update those patterns?

Kind regards

**Comment by twcclegg** [comment]
Please see https://github.com/twcclegg/libphonenumber-csharp/blob/main/CONTRIBUTING.md#checklist-before-filing-an-issue this library consumes Google’s metadata so the issue likely needs to be filed with them.

**Comment by JL-Ikosoft** [comment]
Thanks!
