### ISSUE TITLE
Outdated MetaData version

### ISSUE THREAD

**Issue by madev06** [twcclegg/libphonenumber-csharp#153]
Hi,

The original library has added support for [M2M Dutch numbers](https://github.com/google/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers), since they're used as regular mobile phone numbers sometimes.

When should we expect the next update that includes this?

**Comment by twcclegg** [comment]
Indeed metadata updates we a couple weeks behind. My basic testing shows that these numbers should now be recognized in v8.12.48 which was released a few minutes ago. Thanks for your input.
