### ISSUE TITLE
Extract area codes out of phone number

### ISSUE THREAD

**Issue by BarBenEzra1** [twcclegg/libphonenumber-csharp#156]
Hi :) When having a phone number, for example +12037272643, I would like to extract the area code (203 in this situation) and its name (Connecticut, US). I saw in the tests project of libphonenumbers repo that in order to extract the area code there is a need to initialize some sorted list of type SortedDictionary by providing it the list itself codes and their names. This behavior is unlike extracting the country code, I don't need to pass a list of country codes in order the library will give me the CC of some phone number... isn’t there any built-in file or function for area codes same as for country codes?

**Comment by twcclegg** [comment]
It sounds like what you want is the [PhoneNumberOfflineGeocoder.GetDescriptionForValidNumber](https://github.com/twcclegg/libphonenumber-csharp/blob/main/csharp/PhoneNumbers/PhoneNumberOfflineGeocoder.cs#L221).
However numbers don't necessarily return a state, but rather city and state when the npa+nxx can provide more detail.
See https://dotnetfiddle.net/S2WngL for two examples, your original number that resolves to `Connecticut` and another number that resolves to `Naugatuck, CT`. If you just want the state you could extract the state abbreviation and map from there. 
One thing of note is if a number cannot resolve to a WA city eg `Redmond, WA` it resolves to `Washington State`

**Comment by BarBenEzra1** [comment]
Got it. Since I want everything to be consistent I have this issue that for some numbers I get the area code "New Jersey" (for example) and for some "NJ" (after extraction from the format "SomeCity, NJ"). Is there a way to **always** receive only the state (eg. "New Jersey") or even a function to convert the "NJ" (as input) to "New Jersey" (as output)?
Thank you.

**Comment by twcclegg** [comment]
There isn't directly from the library; I would do something along the line of checking the result for a comma, if present use a dictionary to lookup the state abbreviation to state mapping and if not if not assume it is a state name and then validate. Other than the special case of D.C. I think this would work, but you can look through https://github.com/google/libphonenumber/blob/master/resources/geocoding/en/1.txt to see if there are any other special cases.
