### ISSUE TITLE
Some French numbers returns false for IsValidNumber

### ISSUE THREAD

**Issue by gyoce** [twcclegg/libphonenumber-csharp#159]
When we tried some french numbers starting like : 069605XXXX the lib tell us that the number isn't valid (With PhoneNumberUtil.IsValidNumber) whereas we know someone whose phone number is in that range.

Apparently after a threshold all the next number aren't valid.
You can use this code to see what i'm talking about.
```csharp
    public static void Main(string[] args) {
        var phoneUtil = PhoneNumberUtil.GetInstance();
        for (int phone = 696050000; phone < 696070000; phone++) {
            var phoneNumber = phoneUtil.Parse($"0{phone}", "FR");
            if (phoneUtil.IsValidNumber(phoneNumber)) {
                Console.WriteLine($"0{phone} is a valid number :)");
            }
            else {
                Console.WriteLine($"Phone 0{phone} isn't a valid number :(");
            }
        }        
    }
```
![phones](https://user-images.githubusercontent.com/45860572/188483580-d21298fe-f1cf-4c17-a4be-15c98e82bcc0.png)

**Comment by twcclegg** [comment]
These do not appear to be valid here https://libphonenumber.appspot.com/phonenumberparser?number=0696064276&country=FR please file as issue with Google https://github.com/google/libphonenumber they control the metadata.

**Comment by Abdelrahman-ELGAMAL** [comment]
Hello,

I've a good new for you. It is normal cause theses numbers are automatically redirected to martenique, this means that : 
+3369605XXXX => +59669605XXXX
If you try to validate +59669605XXXX it will work ;)

You can check this info by tryng to call +3369605XXXX  via truecaller.

Can you please (libphonenumber-csharp team) include this exception into french numbers as Martinique is an overseas region of France so bothe of them must be valid for (+596 and +33 ) 

Best regards,
Abdelrahman ELGAMAL
CEO of TOP IT FRANCE

**Comment by twcclegg** [comment]
Apologies @Abdelrahman-ELGAMAL I missed the notification for your comment. Unfortunately I cannot make exceptions / modifications on how numbers are validated (metadata) and requests of this nature have to be made upstream with Google. Instructions for that are [here](https://github.com/twcclegg/libphonenumber-csharp/tree/main/.github/ISSUE_TEMPLATE) .
