### ISSUE TITLE
Country Code is added to NationalNumber in PhoneNumber Object if Number is too short

### ISSUE THREAD

**Issue by zdeluna** [twcclegg/libphonenumber-csharp#165]
Hi, I am trying to call IsValidNumberForRegion for an invalid Italian number and noticed the country code is being added to the national number field in the PhoneNumber object after calling Parse("390000000", "IT"). I think it causing it to be considered a valid number. I have noticed this behavior for BR and SG numbers as well (ex The number is too short but contains a country code, the country code is added to the NationalNumber field). 

```
  PhoneNumber phoneNumber = _phoneNumberUtil.Parse("390000000", "IT");

  if (_phoneNumberUtil.IsValidNumberForRegion(phoneNumber, "IT"))
  {
      return true;
  }
```

**Comment by twcclegg** [comment]
This behavior is seen https://libphonenumber.appspot.com/phonenumberparser?number=390000000&country=IT, given that you would need to submit the issue to Google https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue or https://groups.google.com/group/libphonenumber-discuss.
