### ISSUE TITLE
Document how changes in Google's base library are included or not

### ISSUE THREAD

**Issue by monty241** [twcclegg/libphonenumber-csharp#170]
The text in the issue template:

> [Google demo](http://libphonenumber.appspot.com/)?
> *   Please file an issue with [Google](https://github.com/googlei18n/libphonenumber)

seems to indicate that changes in the metadata are (with some delay) automatically included in this library, but this is not made expicit in readme.md.

Suggestion is to describe whether or not Google's library code changes are followed and with what approximate delay (once per year or so)

This ensures that users don't have to go deeply into the basics to see whether tickets on the Google Issuetracker (for me the trigger was https://issuetracker.google.com/issues/282993649) need extra work here also.

**Comment by twcclegg** [comment]
I can look into putting some updates and improvements to the readme in the next week or so. The metadata isn't updated fully automatically (however fairly close to it) and I usually have it updated in a day or two. The library version matches the Google metadata version.
Actual functional code changes do not currently have a policy for when or if they are ported; bugfixes or other small tweaks are usually done immediately, new features are ported on an ad hoc basis at this point (contributions certainly welcome).

I'm not able to view that Issuetracker link however, if you perhaps have suggestions on better phrasing, I'm intending to mean if you see a behavior that you think is wrong, to then test the number withe the linked demo. If this library and the google demo agree than an issue should be filed with them, if they disagree file an issue here. Happy for suggestions for better ways to explain that, you can find plenty of past issues where I have to point people over.

**Comment by monty241** [comment]
Thank you for looking into it. Just a small note like the comment above would be sufficient for me getting to understand the maintenance process without bothering maintainers.

The Issuetracker link is just some bug report on the Dutch number representation, which might or might not make it into an improvement for libphonenumber. The Google original version has that issue too, so that's why it was reported primarily there since that might benefit the most people.
