### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by KostaMadorsky** [twcclegg/libphonenumber-csharp#171]
It would be great if you could publish signed assemblies in line with [Microsoft's guidance for open-source libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries).

Here's the guide on [How to: Sign an assembly with a strong name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name).

Thanks! 🙂

**Comment by KostaMadorsky** [comment]
This may cause binary breaking change...

**Comment by twcclegg** [comment]
Duplicate of #53
