### ISSUE TITLE
Make metadata update and publish new version fully automatically

### ISSUE THREAD

**Issue by twcclegg** [twcclegg/libphonenumber-csharp#172]
Currently metadata update is [semi-automated ](https://github.com/twcclegg/libphonenumber-csharp/blob/main/csharp/lib/update.sh). The remaining work is to have this script run automatically, likely triggered via email from libphonenumber-discuss@googlegroups.com "libphonenumber {VERSION} released" or polling https://github.com/google/libphonenumber/releases.

**Comment by wmundev** [comment]
Hey @twcclegg 
i have a PR to resolve this issue up - https://github.com/twcclegg/libphonenumber-csharp/pull/192

let me know what you think, hope it helps!
