### ISSUE TITLE
New Kazakhstan country code.

### ISSUE THREAD

**Issue by zhdamorev** [twcclegg/libphonenumber-csharp#173]
Hello, there was an announcement, that Kazakhstan is moving to new phone country code "+997" till 2025 and while moving it is possible to use in Kazakhstan old "+7" code. Are you going to maintain this new code for Kazakhstan? What the version are you going to implement it in?

**Comment by twcclegg** [comment]
This should be a question for https://github.com/google/libphonenumber / libphonenumber-discuss@googlegroups.com, I do not control the metadata.
