### ISSUE TITLE
IsPossibleNumberForTypeWithReason returns valid mobile when IsValidNumber returns invalid

### ISSUE THREAD

**Issue by LeoJHarris** [twcclegg/libphonenumber-csharp#181]
Trying to validate an Australian number such as this `0911223302` which should be invalid, I have followed this comment https://github.com/twcclegg/libphonenumber-csharp/issues/112#issuecomment-584308812 which shows the validation indicating the mobile is invalid using `IsValidNumber` which would be correct but using `IsPossibleNumberForTypeWithReason` seems to indicate the mobile is valid. I would like to get the reason and output to the user hence I am using the `IsPossibleNumberForTypeWithReason` method.

See example per below, it shows as valid and invalid for the same number:

https://dotnetfiddle.net/IhPI72 - shows valid
https://dotnetfiddle.net/TRCAFw - shows invalid

I would be keen to know why once is working whilst the other is not, we are checking against Australian mobiles only. Beginning with `09` should be invalid

**Comment by twcclegg** [comment]
[Google](https://github.com/google/libphonenumber)'s app shows the same https://libphonenumber.appspot.com/phonenumberparser?number=%2B61480231902 https://libphonenumber.appspot.com/phonenumberparser?number=0911223301&country=AU you would need to ask them; I don't control the the metadata.
