### ISSUE TITLE
Valid US number is resulting in IsValid to false

### ISSUE THREAD

**Issue by fireole** [twcclegg/libphonenumber-csharp#182]
Has anyone seen US Numbers getting kicked to IsValid = false?

I have a valid number that I have tried different phone formats and getting the same result.

the countryCode is set to "US".

I would put the number, but don't want to put the clients number out here.  Just seeing if others have ran into this.

`                var phoneNumberUtil = PhoneNumberUtil.GetInstance();
                var phoneNumber = phoneNumberUtil.Parse(phone, countryCode);

                var numberOptions = new CleanNumber
                {
                    IsValid = phoneNumberUtil.IsValidNumber(phoneNumber),
                    E164 = phoneNumberUtil.Format(phoneNumber, PhoneNumberFormat.E164),
                    Raw = phoneNumber.NationalNumber.ToString(),
                    Pretty = phoneNumberUtil.Format(phoneNumber, PhoneNumberFormat.NATIONAL),
                    Mobile = phoneNumberUtil.FormatNumberForMobileDialing(phoneNumber, countryCode, true)
                };`

**Comment by twcclegg** [comment]
It's problematic to look into without the number in question. Have you tried it with https://libphonenumber.appspot.com/? Also you could look at https://dotnetfiddle.net/8synrr. If you get invalid from the appspot link then you'd have to take the issue up with Google https://groups.google.com/g/libphonenumber-discuss.

**Comment by fireole** [comment]
I just tried with https://libphonenumber.appspot.com/ and comes back valid.  

Can I send you the number privately?

**Comment by fireole** [comment]
I emailed the number to you.

**Comment by fireole** [comment]
it was fixed my updating the library. thanks for your help
