### ISSUE TITLE
Parsing phone number as valid when it starts with _

### ISSUE THREAD

**Issue by PeteMcGann** [twcclegg/libphonenumber-csharp#183]
In order to validate a phone number the library requires a PhoneNumber instance which (in my case) is created using: 
var phoneNumber = phoneUtil.Parse(number, "GB");

I then test the number using this code:

return phoneUtil.GetNumberType(phoneNumber) == PhoneNumbers.PhoneNumberType.MOBILE;

Unfortunately, if a phone number starts with an underscore the Parse function will ignore it and parse the number as if it wasn't there, which in turn means the number is considered valid when it isn't.

**Comment by twcclegg** [comment]
I believe https://github.com/twcclegg/libphonenumber-csharp/pull/184 should resolve the issue. Presuming that, the change should be out in the 8.12.24 release.

**Comment by PeteMcGann** [comment]
Perfect thank you!

**Comment by PeteMcGann** [comment]
By any chance do you have an ETA on v8.13.24?

**Comment by twcclegg** [comment]
Probably pretty soon, release schedule follows https://github.com/google/libphonenumber/releases

**Comment by PeteMcGann** [comment]
I just installed v8.13.24 and unfortunately I have the same issue - when a number starts with _ the phoneUtil.Parse(number, "GB") method removes it, and hence it passes validation - am I doing something wrong?

**Comment by PeteMcGann** [comment]
So I guess I'm just stuck with it! Time to use another library methinks..

**Comment by twcclegg** [comment]
Sorry, I’ve been out of town. Fix didn’t get merged in for 8.13.24, it will be in 8.13.25 which should be able to be released Sunday.

**Comment by PeteMcGann** [comment]
Ok no problem, thanks.

**Comment by twcclegg** [comment]
So v8.13.25 is out, and the logic for this better matches the Java version; however I overlooked that the Java version https://libphonenumber.appspot.com/phonenumberparser?number=_%2B14429994455 a preceding `_` does not change the behavior.
I could add something to https://www.nuget.org/packages/libphonenumber-csharp.extensions/ but would need a more generalized use case and name for it, also using the extension library can make namespacing annoying and I don't personally consume it.

**Comment by PeteMcGann** [comment]
Thanks for that, much appreciated - I've modified my codebase to just remove anything other than a + from the beginning of a number before validating it, but this will come in handy anyway.  Cheers.
