### ISSUE TITLE
Does Phone Number Meta Data need to be a compiled resource?

### ISSUE THREAD

**Issue by t3dodson** [twcclegg/libphonenumber-csharp#20]
### Do the resources need to be compiled into this assembly?

Over time as new area codes are added and the version of this package changes I am forced to recompile to properly reference the new version of the dll.

### Are external resources consistent with the design goals of this project? 

I don't think the logic behind this lookup should change with the addition of area codes.

#### Would this repo accept a PR that moves resources to an external file?

**Comment by landrix** [comment]
any help is welcome

**Comment by aidanbebbington** [comment]
I think it would be great to have the metadata updated separately somehow.
How were you thinking?

**Comment by t3dodson** [comment]
@aidanbebbington The implementation of it has some options. I'm not very familiar with your code base so please excuse me if I state something incorrectly.

I've identified four methods that read from the assembly manifest to get a resource stream.
The stream is passed off to other methods to construct the meta data.

`
    .GetManifestResourceStream(... // search in files for these method calls
`

I could see a solution where external xml files sit along side the dll (can a nuget package do this?)

There could be error handling. If the file cannot be read or found maybe still keep the compiled resource as a backup.

This way if a consumer of this package doesn't want to recompile and potentially change their code they could just drop in a newer version of the xml file and we would pull the new info.

There could be concerns around if the structure of the resources changes frequently.

**Comment by aidanbebbington** [comment]
That sounds fair enough. Would be amazing if it updated itself too, but
that's probably a bit much. There can sometimes be code changes also, but
they are typically just metadata changes. I'm not sure if the version
numbering scheme tells anything about if it's a minor metadata update or a
structural change.

**Comment by t3dodson** [comment]
I found some docs on packaging files alongside the dll
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#adding-a-readme-and-other-files 

@aidanbebbington Would it be fair to try and parse the xml file and if it doesn't exist or it fails then fallback on the compiled resource?

I'm hoping this enhancement would only require some minimal logic around reading the metadata and maybe a modification to the build script/nuget script.

**Comment by aidanbebbington** [comment]
That seems fair to me. Just out of curiosity, does Nuget have any
capability to also download files from the web during install?

**Comment by t3dodson** [comment]
I found [this article](http://www.vicesoftware.com/nuget/creating-a-nuget-package-that-will-install-files-relative-to-the-solution/#Automatically_Running_PowerShell_Scripts_During_Package_Installation_and_Removal) we can create an install.ps1 script that runs when the package is installed. Powershell could download a file pretty easily.

My thought was have the most recent xml for a version packaged with the dll. What file are you thinking could be downloaded at install time?

**Comment by aidanbebbington** [comment]
Don't know if it'd be too weird, but perhaps the XML data could be
downloaded. Would save forgetting to update the nuget package all the time.
I guess ideally it wouldn't just be at install time, but dont know what
other time could be used to do it.

**Comment by twcclegg** [comment]
Is the demand for this mitigated by having new versions of the package released very shortly after each metadata release from Google?
