### ISSUE TITLE
GetNumberType always returns UNKNOWN 

### ISSUE THREAD

**Issue by mahranben** [twcclegg/libphonenumber-csharp#203]
Hello, 

I'm new to this library so i'm not sure if it something i'm doing wrong. 
I use release 8.13.25 from Nuget
```

var numberProto = phoneUtil.Parse("06xxxxxxxx", "33");
var type = PhoneNumberInstance.GetNumberType(numberProto);
```
type is always UNKNOWN

looking into the code of GetNumberType 

```
  public PhoneNumberType GetNumberType(PhoneNumber number)
    {
      string regionCodeForNumber = this.GetRegionCodeForNumber(number);
      return !this.IsValidRegionCode(regionCodeForNumber) && !"001".Equals(regionCodeForNumber) ? PhoneNumberType.UNKNOWN : this.GetNumberTypeHelper(this.GetNationalSignificantNumber(number), this.GetMetadataForRegionOrCallingCode(number.CountryCode, regionCodeForNumber));
    }
```
but in my case regionCodeForNumber is "FR" so this condition 
`!"001".Equals(regionCodeForNumber) `
 is never met. Also, i think this condition can never be meet as regionCodeForNumber could not be equal to "001" ?

**Comment by twcclegg** [comment]
Is the code snippet you are using exactly the above "06xxx..."? Because `Parse` is for parsing specific numbers numbers. Also the second parameter to `Parse` is region code not country code eg "FR".
The below outputs MOBILE
```c#

		var number = phoneUtil.Parse("644621316", "FR");
		Console.WriteLine(phoneUtil.GetNumberType(number));
```

**Comment by mahranben** [comment]
@twcclegg Sorry i got mixed up in the example. Also the number i was testing is not a actual number. 
I managed to get it working. I close this issue. 
thanks
