### ISSUE TITLE
Breaking change in PhoneNumberUtil.Normalize

### ISSUE THREAD

**Issue by Drake53** [twcclegg/libphonenumber-csharp#206]
A breaking change was introduced in the following commit: https://github.com/twcclegg/libphonenumber-csharp/commit/2c256a85359bb41d5a9bc71021c970f89864ff9a

The old / .NET standard implementation uses StringBuilder, which accepts a `null` string. The new / .NET (core) implementation uses `number.Length`, which will throw a NullReferenceException if the input string is `null`. Note that this also means that these two implementations currently behave inconsistently.

It would also be nice if you could enable the nullable reference types feature: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references
This helps prevent NullReferenceExceptions not only in this project, but also in projects which use this library. In my case, even though the compiler knew the input string could be `null`, I got no warning because this library is nullable oblivious.

**Comment by twcclegg** [comment]
The null reference issue should be fixed by the PR linked above. If you could file a separate issue for adding nullable that indeed would be a good enhancement.

**Comment by Drake53** [comment]
Thanks for the quick response.
I made a separate issue for nullable reference types.
