### ISSUE TITLE
Enable nullable reference types

### ISSUE THREAD

**Issue by Drake53** [twcclegg/libphonenumber-csharp#208]
See https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references
This feature was introduced in C# 8.0 and, if enabled, helps prevent NullReferenceExceptions by giving compiler warnings when a NullReferenceException may occur.
Made a separate issue for this as requested in #206

**Comment by wmundev** [comment]
nullable references have been enabled on files where it is possible and disabled where it will take a longer while to migrate - https://github.com/twcclegg/libphonenumber-csharp/blob/main/csharp/PhoneNumbers/PhoneNumbers.csproj#L29

feel free to reopen if you have any other questions with this, thanks for reporting
