### ISSUE TITLE
Vietnamese phone number does not validate

### ISSUE THREAD

**Issue by timdhaeyer** [twcclegg/libphonenumber-csharp#213]
I'm trying to validate a Vietnamese phone number, but I keep getting validation errors.
The number is correct since we can actually call it. I'm sharing a picture of the phone number since I don't want it searchable via Google :-)
![image](https://github.com/twcclegg/libphonenumber-csharp/assets/47555315/6535849c-5bd8-4e4b-a4d5-5e07078efc3c)

**Comment by twcclegg** [comment]
This behavior seems to match https://libphonenumber.appspot.com (not linking directly to your number), as such you'll need file an issue with Google https://groups.google.com/g/libphonenumber-discuss
