### ISSUE TITLE
French mobile numbers with prefix "07" are not detected as mobile numbers

### ISSUE THREAD

**Issue by madmox** [twcclegg/libphonenumber-csharp#214]
French mobile numbers can start with "06" or "07" ([source](https://en.wikipedia.org/wiki/Telephone_numbers_in_France)). The library only detects mobile numbers with prefix "06".

Example:
```csharp
using PhoneNumbers;

PhoneNumberUtil PARSER = PhoneNumberUtil.GetInstance();

PhoneNumber parsedNumber1 = PARSER.Parse("+33612345678", defaultRegion: null);
Console.WriteLine(PARSER.GetNumberType(parsedNumber1)); // => MOBILE

PhoneNumber parsedNumber2 = PARSER.Parse("+33712345678", defaultRegion: null);
Console.WriteLine(PARSER.GetNumberType(parsedNumber2)); // => UNKNOWN
```

`libphonenumber-csharp` version: `8.13.26`

**Comment by twcclegg** [comment]
This behavior seems to match https://libphonenumber.appspot.com/phonenumberparser?number=%2B33712345678, as such you'll need file an issue with Google https://groups.google.com/g/libphonenumber-discuss

**Comment by madmox** [comment]
[Issue](https://issuetracker.google.com/issues/316476490) created.
