### ISSUE TITLE
docs: codecov badge on README leads to old trunk branch "master" instead of the new "main" branch

### ISSUE THREAD

**Issue by wmundev** [twcclegg/libphonenumber-csharp#223]
A minor issue exists in the codecov badge in the README, it links to https://app.codecov.io/gh/twcclegg/libphonenumber-csharp which points to code coverage for the master branch instead of main, which is the new default branch

perhaps a setting needs to be updated in the codecov website?

**Comment by twcclegg** [comment]
Indeed that was the case, thanks for noticing.
