### ISSUE TITLE
Upgrade from 8.3.1 to 8.3.1.1 - Compiler Error CS0012

### ISSUE THREAD

**Issue by tedebus** [twcclegg/libphonenumber-csharp#24]
After the update to the last version  (from 8.3.1 to 8.3.1.1) using NuGet, Visual Studio compiler raises error CS0012 in my project, looking for System.Runtime.

> The type '_type_' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime', Version=4.0.0.0, Culture=neutral

The downgrade to version 8.3.1 works fine.
I'm using .Net 4.0 (not client)

**Comment by RaoulHolzer** [comment]
Same problem here, since the newst VS2017.2 Update

**Comment by twcclegg** [comment]
I believe this is resolved in new versions. I will be closing this issue in the coming weeks unless I hear otherwise.
