### ISSUE TITLE
Personal numbering

### ISSUE THREAD

**Issue by tedebus** [twcclegg/libphonenumber-csharp#25]
This library doesn't support personal numbering.
https://en.wikipedia.org/wiki/Personal_numbering

I'm trying with Spain's numbers, for example: +345906xxxxxxxxx it doesn't recognize them

**Comment by twcclegg** [comment]
Can you retest with the latest version, 8.6.0? If it still doesn't work but does come up correctly using the Google sample https://libphonenumber.appspot.com/? If so if you can send me an actual number I can look into it.

**Comment by tedebus** [comment]
Hi Thomas, I'm sorry, it doesn't work.
I tried +345901000xxxxxx
I can't write the whole number here but if you want I could send it to you by mail.

**Comment by tedebus** [comment]
Hi Thomas, another question for you: why library is not more available for .net fw  v4.0?

**Comment by twcclegg** [comment]
You can DM the whole number if you like. I just pushed a change and published 8.6.0.1 which targets net40 instead of net45.

**Comment by twcclegg** [comment]
I intend to have the next version move back to targeting net35 as it was before the port to netstandard, I overlooked a build warning that 4.0 lacks Linq. @tedebus

**Comment by twcclegg** [comment]
I'm not finding a good way to build 3.5 along with netstandard, is there a good reason not to stick with 4.5?

**Comment by Danthar** [comment]
Which version of netstandard are you going to support? Because you might find that supporting netstandard, and .net35 might not be feasable :P https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by tedebus** [comment]
Hi thomas, sorry for the delay.
I've sent you an email.
Maybe I'm so stupid but... is there a way to send private messages here?

**Comment by twcclegg** [comment]
@tedebus Yeah, I've looked before too, doesn't seem there is a DM ability. I'm not seeing an email anywhere, you can send it to my username at gmail. Also the nuget page has a contact owners mailto.

**Comment by tedebus** [comment]
Well, I wrote to your public mail here on github: thomas dot clegg at freedomvoice dot com.
I'll write you again on gmail.

**Comment by twcclegg** [comment]
Got it, I'll take a look. Thanks for pointing that out, I don't have access to that email anymore.

**Comment by twcclegg** [comment]
Both http://libphonenumber.appspot.com/phonenumberparser?number=59065xxxxxxxx&country=ES and http://libphonenumber.appspot.com/phonenumberparser?number=%2B3459065xxxxxxxx show up as TOO_LONG. You can open an issue with https://github.com/googlei18n/libphonenumber/ if you believe that is not the case, however per https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain#Personal_numbering personal numbers should be a 5 followed by eight digits not twelve.
