### ISSUE TITLE
New regulation for phone number prefixes in Australia

### ISSUE THREAD

**Issue by leonardonl** [twcclegg/libphonenumber-csharp#259]
There is a new Australian regulation concerning phone number prefixes:
Phone numbers starting with 04{0-8} are accepted, but 049 and 05{1-9} are rejected, and according to the [AUS telecom numbering plan](https://www.legislation.gov.au/F2015L00319/latest/text), 04{0-9} and 05{0-9} must be accepted. A similar situation happens when you try +6149 or +615{0-9} (or +61049 and +6105{0-9}).

**Comment by twcclegg** [comment]
Metadata for this library is controlled by Google. See https://github.com/twcclegg/libphonenumber-csharp/blob/main/.github/ISSUE_TEMPLATE/bug_report.md for opening an issue with them.
