### ISSUE TITLE
Get Country Name by country code

### ISSUE THREAD

**Issue by gilleslabelle** [twcclegg/libphonenumber-csharp#260]
Is is possible to get the full country name with a country code?

**Comment by twcclegg** [comment]
Unfortunately it is not. This library does not intend to supply information beyond what is present here http://www.libphonenumber.appspot.com/phonenumberparser?number=%2B14429994455.
Also note that country code doesn’t map 1:1 with a country (most notably US & Canada share +1 for NANP).
