### ISSUE TITLE
New phone number format for Benin not supported

### ISSUE THREAD

**Issue by bertsch-ronja-office** [twcclegg/libphonenumber-csharp#272]
Benin changes its phone number format - beginning 30 November 2024, all existing telephone numbers in Benin will add "01" in front of them.

Source: https://en.wikipedia.org/wiki/Telephone_numbers_in_Benin

The newest version of libphonenumber-csharp (8.13.49) does rate the new format (example phone number +2290140123456) as invalid (whereas the old format +22940123456) works.

**Comment by wmundev** [comment]
hi @bertsch-ronja-office , try the new version, it should work now - 
http://libphonenumber.appspot.com/phonenumberparser?number=%2B2290140123456

https://github.com/twcclegg/libphonenumber-csharp/releases/tag/v8.13.51

**Comment by wmundev** [comment]
closed as resolved with the new metadata release, feel free to reopen if its still not resolved

**Comment by bertsch-ronja-office** [comment]
@wmundev  Thanks, the new format works now.

Still we are having an issue with parsing the E164 format - in the link you sent me the E164 is: +2290140123456


But using the IsE164 method, the leading 0 is stripped, it returns the following as E164: +229140123456

var e164PhoneNumber = phoneNumberUtil.Format(phoneNumber, PhoneNumberFormat.E164);

What is now the right E164 number?
