### ISSUE TITLE
Consider adding portable version of library

### ISSUE THREAD

**Issue by mstyura** [twcclegg/libphonenumber-csharp#3]
It would be nice to have version usable from portable projects (including UWP)

**Comment by twcclegg** [comment]
Let me know if there is still desire for this to be on the roadmap, otherwise I will be closing this in the coming weeks.

**Comment by mstyura** [comment]
I don't thinks it's relevant anymore, but maybe .NET Standard support is important now.

**Comment by twcclegg** [comment]
net standard has been supported in the last several releases.
