### ISSUE TITLE
Update Project Site url on the nuget package page

### ISSUE THREAD

**Issue by andreymir** [twcclegg/libphonenumber-csharp#30]
Could you update a Project Site url on the nugt package page https://www.nuget.org/packages/libphonenumber-csharp? Currently, it is pointing to the old bitbucket repository which is confusing, because the repository has not been updated since 2012, but 12 new nuget packages have been published since then.

**Comment by twcclegg** [comment]
This was an oversight while working to get a netstandard version published, it should be fixed now.
