### ISSUE TITLE
Leading 0 causes incorrect parsing

### ISSUE THREAD

**Issue by Colegreen** [twcclegg/libphonenumber-csharp#39]
I'm comparing the output to what I get from here: http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Very simple code, just doing the followig:

PhoneNumberUtil util = PhoneNumberUtil.GetInstance();
PhoneNumber test = util.Parse("044 668 18 00", "CH");
//PhoneNumber test = util.Parse("0111 111 1111", "GB");
Debug.Print(util.Format(test, PhoneNumberFormat.NATIONAL));

(Both versions cause the issue).

I am expecting the output to be "044 668 18 00" but instead it is "0446681800"

I went back to hash fa23720bea8213123a93436d688b59f2cd2ca56e and it seemed to be working properly there

**Comment by BenKmann** [comment]
I agree, we have the same Problem. 
I get it since the 8.8.x Releases. 
8.7.x is working fine.

**Comment by twcclegg** [comment]
The fix for this will be released with 8.8.4 once the upstream version is officially released, which I expect to be in the next day or so.
