### ISSUE TITLE
When First time parse phone number its taking time but second cannot..

### ISSUE THREAD

**Issue by jaganjan** [twcclegg/libphonenumber-csharp#4]
var phoneNumber = utility.Parse(mobNo, region);

**Comment by julesx** [comment]
i am seeing this same behavior using Xamarin Forms on Android.
The first number parse takes upwards of 10 seconds, afterwards it is fine.

Seems to have no issues on iOS.

**Comment by aidanbebbington** [comment]
That's interesting.  The binary reads it's "metadata" from XML files embedded in the DLL.  I think that occurs the first time it's required.  Likely that something about the environment is holding that process up.

**Comment by tedebus** [comment]
It's a problem I've known for some time. My solution has always been to launch a task at boot with the sole purpose of testing a number causing library initialization.

**Comment by Ripper555** [comment]
@aidanbebbington I'm having the exact same problem using Xamarin Forms on Andriod with the load time. Load time too long to use. I have found a fork that fixes the problem: 

https://github.com/greshnoff/libphonenumber-csharp

Changes my initial use from 3.7 seconds down to around 0.27 (270 milliseconds). I would love for you to merge the changes to fix the problem. I don't have the time to help as I wish I did.

**Comment by iamwyza** [comment]
Man, I would love this to switch to protobuf for the metadata.  My init use runs at about 1.5-2s and having it load in .25s would be wonderful.

**Comment by twcclegg** [comment]
@iamwyza I agree unfortunately it is relatively low on my todo list, first I want to get it up to feature parity. PRs are welcome though.

**Comment by iamwyza** [comment]
It looks like someone already did the fork and the work.  I'm guessing they just never submitted a pull request? or is their fork too old to merge?

**Comment by twcclegg** [comment]
Where do you see this fork? A PR should be able to be made, how mergeable it would be is another question

**Comment by iamwyza** [comment]
Ripper linked it in the comment above mine, but here it is for simplicity:

https://github.com/greshnoff/libphonenumber-csharp

**Comment by Architekt909** [comment]
Any update on this? Still takes a long time to parse a number on Android the first time.

**Comment by twcclegg** [comment]
Unfortunately not really, at the moment I have a few projects that take priority over this and currently I am the sole maintainer of the library. I have some work in progress but it should be split in to multiple smaller PRs.

**Comment by KevinHu-au** [comment]
@twcclegg, any update on this? I still have this issue on Xamarin.Android. Thanks

**Comment by twcclegg** [comment]
I haven't looked at it in quite a while. The subtle differences between binary serialization in java and dotnet make it a bit more problematic than it would be otherwise.

**Comment by CPlusPlus17** [comment]
Same problem on blazor wasm project, takes about 10 seconds first time. Unusable at this stage.
