### ISSUE TITLE
Strongly-named DLLs?

### ISSUE THREAD

**Issue by qinxi-microsoft** [twcclegg/libphonenumber-csharp#48]
Being the most often updated and most popular port of libphonenumber to C#, this port is currently considered to be the port of choice in the long term for a project which requires strong names for all its component DLLs. Therefore, we would be very thankful if the DLLs could be made strongly named, so that it could be used for a wider range of projects with higher requirements for safety. Thank you in advance!

**Comment by twcclegg** [comment]
https://github.com/twcclegg/libphonenumber-csharp/issues/18
