### ISSUE TITLE
New Longer NZ Mobile failing validation

### ISSUE THREAD

**Issue by Mitchies1970** [twcclegg/libphonenumber-csharp#49]
NZ now allows 7 **_or 8_** digits after the network code. 

The library is failing the validation when 8 chars after the network code. 

See below for example number that fails:

Fails (but is valid - see here: http://www.tnzi.com/numbering-plan)
+642123456789

**Comment by twcclegg** [comment]
The google example app shows the number as possible but not valid http://libphonenumber.appspot.com/phonenumberparser?number=%2B642123456789 if you find this library has results that differ from the example please file a new issue here. If you believe that the example app is wrong please open an issue here: https://github.com/googlei18n/libphonenumber

**Comment by Mitchies1970** [comment]
Thank you, I have filed new issue as you suggested: https://github.com/googlei18n/libphonenumber/issues/2062
