### ISSUE TITLE
Some numbers throw exception

### ISSUE THREAD

**Issue by Ketan-Desai** [twcclegg/libphonenumber-csharp#50]
Hi,

Please check following numbers if they produce consistent output, throw exception, etc...

00870773924761
00211912378429

Thanks

**Comment by twcclegg** [comment]
After some digging those numbers appear to be from Inmarsat and South Sudan respectively. All numbers, in order to parse need to be either in E164 format (+870773924761, +211912378429), or have their region code provided. For South Sudan "SS", for Inmaset I can find reference to one but "GB" works.

**Comment by Ketan-Desai** [comment]
Hi Tom,

As I understand, the specified numbers are in E164 format.
So without specifying region code, it can be parsed.

But it throws an exception on my side.

Here is the code snippet, please advise if it needs any correction...

```
        public static bool TryParse(string s, out Number number)
        {
            number = null;

            //if (s == null || !s.All(char.IsDigit))
            //    return false;

            s = "+" + s.Substring(2);

            var phoneNumberUtil = PhoneNumberUtil.GetInstance();

            if (phoneNumberUtil.IsPossibleNumber(s, null))
            {
                var phoneNumber = phoneNumberUtil.Parse(s, null);

                if (phoneNumberUtil.IsValidNumber(phoneNumber))
                {
                    string regionCode = phoneNumberUtil.GetRegionCodeForNumber(phoneNumber);

                    // +870773924761 Region Code = '001'
                    if (InternationalNumberManager.RegionCountryNameDictionary.TryGetValue(regionCode, out string region))
                    {
                        string desc;

                        // +211912378429 Exception
                        try
                        {
                            string cityState = PhoneNumberOfflineGeocoder.GetInstance().GetDescriptionForValidNumber(phoneNumber, Locale.English);

                            desc = ((cityState == region) ? cityState : cityState + ", " + region) + " (International)";
                        }
                        catch
                        {
                            desc = region + " (International)";
                        }

                        number = new InternationalNumber { Code = phoneNumber.CountryCode, Description = desc };

                        return true;
                    }
                }
            }

            return false;
        }
```
The input is like 00870773924761, 00211912378429, etc...
InternationalNumberManager.RegionCountryNameDictionary is Dictionary<string, string> type.

Thanks

**Comment by twcclegg** [comment]
Copying your code above, of the few numbers I've tried nothing throws an exception. It returns false if the region code isn't in the dictionary. The first number returns a region code of "001" (quite the curious number you've selected), the second "SS", as long as both of these are in the dictionary both work without error and return true for me.

**Comment by Ketan-Desai** [comment]
Hi Tom,

Thanks for verifying the code and numbers.

Why there is an issue with 00211912378429 number.
The try/catch block is added for it specifically.

Thanks
