### ISSUE TITLE
how to validate the phone number without country code?

### ISSUE THREAD

**Issue by touseefbsb** [twcclegg/libphonenumber-csharp#52]
I'm using this library for a uwp project.

The Java counterpart works fine with the PhoneNumberUtil.getInstance().parse("phonenumber here","") format, automatically determining the country code. However the .Net version (this) requires a valid country identifier, which I unfortunately do not have specified for the phone numbers.

How can I do this with this library?

**Comment by touseefbsb** [comment]
i updated to latest version and I was able to solve this. sorry for the disturbance :)

**Comment by brolaugh** [comment]
For future googlers:

You may simply provide `"ZZ"` as a second argument as such:
 `PhoneNumberUtil.getInstance().parse("+1-202-555-0178","ZZ") `

**Comment by twcclegg** [comment]
If the number is E164 `null` also works.

**Comment by markleavesley** [comment]
Providing "ZZ" does not work if a string is numeric but not a valid phone number such as "1234". In the situation where you have no idea what country a number may be from it would be nice to simply ask "Is this a valid E164 number?"

**Comment by twcclegg** [comment]
I believe what you're looking for is
```c#
phoneUtil.IsPossibleNumber("1234", "ZZ");
```
Which as expected, returns false.

**Comment by markleavesley** [comment]
Thanks!
