### ISSUE TITLE
Short number functionality missing

### ISSUE THREAD

**Issue by asaf0000** [twcclegg/libphonenumber-csharp#54]
Hello,

The short number functionality is missing from the library.

In the original library or using this checker: 
https://libphonenumber.appspot.com/phonenumberparser?number=911&country=US

For example, if I want to check if 911 is a valid number, then it says that is INVALID.
But if I see the short number results they say that it is a valid short number.

The library only has two function and is missing the others that are really useful:
**isPossibleShortNumber()
isValidShortNumber()
isPossibleShortNumberForRegion()
isValidShortNumberForRegion()**

Please help adding this functionality!
Thank you in advance

**Comment by twcclegg** [comment]
The whole of short number number parsing is indeed yet to be ported. That functionality along with the issues raised in #4, #41, and general geocoding are on my todo list.

**Comment by twcclegg** [comment]
Done 😀
