### ISSUE TITLE
Unable to open sln in either 2015 or 2017

### ISSUE THREAD

**Issue by pmcevoy** [twcclegg/libphonenumber-csharp#55]
Hi,
I'm trying to open the sln to browse code and getting failures straight away in VS 2015:

```
C:\Source\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Source\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj

C:\Source\libphonenumber-csharp\csharp\PhoneNumbers.Test\PhoneNumbers.Test.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Source\libphonenumber-csharp\csharp\PhoneNumbers.Test\PhoneNumbers.Test.csproj
```

Looking at the csproj files, they are in a format that I am completely unfamiliar with and don't have any "Compile" items listed.  Thinking this was the new 2017 file format, I opened the sln there and it also complained:

```
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - PhoneNumbers, "C:\Source\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj"


Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - PhoneNumbers, "C:\Source\libphonenumber-csharp\csharp\PhoneNumbers.sln"
```

I've looked at earlier versions of the csproj and it seems to have changed March 11 2017 and then March 13 says "Converted to 2017" - but it does not open in 2017.

**Comment by twcclegg** [comment]
Are you using the latest 2017, 15.5.7? Really anything up to date to the last six months or more should be fine. The csproj files are in netstandard/netcore format https://docs.microsoft.com/en-us/dotnet/core/tools/csproj. It's a bit out of date (still 1.0 not 2.0) but can you open https://github.com/dotnet/core/tree/master/samples/helloworld?

**Comment by pmcevoy** [comment]
Hmm... Here is the 2017 info:

```
Microsoft Visual Studio Professional 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional
```

When I attempt to open that hello world sample, I get this:

```
The selected file cannot be opened as a solution or project. Please select a solution file or a project file.
```
Baffled.  I accept this is not your issue then.. but confused where to go from here..

Granted, I only installed 2017 this morning via Chocolatey so that I could browse your code (we're still on 2015 in work)

**Comment by pmcevoy** [comment]
Ah.. seems that the choco package only installs bare minimum (Core Editor) and extra command line params are needed to enable .net dev..

**Comment by twcclegg** [comment]
I like choco for a lot of thing but would recommend the native VS installer for Visual Studio, and make sure all the netstandard check boxes are checked. As an aside, while you need new-ish (and complete) version of Visual Studio to open the solution, the nupkg is backwards compatible down to .net40.

**Comment by pmcevoy** [comment]
```
choco install visualstudio2017-workload-netweb
```
and I was able to open your sln...  

Cheers and thanks for maintaining this project
Pete
