### ISSUE TITLE
Deprecating GlobalPhone in favor of libphonenumber-csharp?

### ISSUE THREAD

**Issue by wallymathieu** [twcclegg/libphonenumber-csharp#57]
Hi
There is currently a port of the Ruby Gem GlobalPhone in c#. Would it make sense to deprecate [GlobalPhone](https://github.com/GlobalPhone/GlobalPhone) (since there has not been any interest in making any pull requests) and point to libphonenumber-csharp? This is related to https://github.com/GlobalPhone/GlobalPhone/issues/24

**Comment by twcclegg** [comment]
I see no reason why not, assuming that the migration path isn't too onerous. But given the age of the last release there's been quite a deal of updates it would be missing, 833 is the first thing that comes to my mind.

**Comment by wallymathieu** [comment]
Having a migration path would be nice. Another alternative is to use reimplement `GlobalPhone` as a set of extension methods and or wrappers to make it more c#-y.

**Comment by wallymathieu** [comment]
What do you think is the best way forward?

**Comment by wallymathieu** [comment]
Or is it only the builder that looks a bit non c#-y?

**Comment by twcclegg** [comment]
The wrapper is certainly an option, would want to use [floating versioning](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions) to not need to update every time there's new metadata. This port tries to do it's best to stay true to the Java source and its API while also adhering to C# styles and paradigms. The builder for PhoneNumber is the only major place that those two are particularly at odds. I use use `phoneNumberUtil.Parse([E164 Number], null)` in place of what ideally would be a constructor. The PhoneNumber class is autogenerated from the Google proto and I would rather not diverge from that.

**Comment by wallymathieu** [comment]
Yes, that makes sense. I've not had the time to look into making any changes related to this.
