### ISSUE TITLE
Does this lib support UWP?

### ISSUE THREAD

**Issue by yowang** [twcclegg/libphonenumber-csharp#59]
When I install this lib by NuGet in the UWP project, I get the error message: "Some packages are not compatible with UAP,Version=v10.0"

**Comment by AwsomeCode** [comment]
What is your Min and Max Target framework?

**Comment by twcclegg** [comment]
It seems that UWP should be compatiable with .NET Standard 2.0 https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/ The library currently targets net35, net40, netstandard1.3, and netstandard2.0.

**Comment by twcclegg** [comment]
This was duplicated by #61 Hopefully https://ci.appveyor.com/project/twcclegg/libphonenumber-csharp/build/8.9.6-12d17b6/artifacts fixes it and if so it will be in releases >=8.9.7.
