### ISSUE TITLE
.NET Core Support??

### ISSUE THREAD

**Issue by cindro** [twcclegg/libphonenumber-csharp#6]
I recently upgraded an app of mine to ASP.NET 5 .NET Core, then realised that this great library didn't support DNXCore.

Is this support coming soon?

**Comment by aidanbebbington** [comment]
That's no good at all, hadn't caught up to the world of 5.0 to be honest.
What do you expect in terms of support? Does it simply not build or is
there something specific?

**Comment by cindro** [comment]
This is a great library, been using it for while now. I am now upgrading one of my apps but unable to utilise libphonenumber-csharp, I get below error.

The dependency libphonenumber-csharp 7.0.11 does not support framework DNXCore,Version=v5.0

There is no great alternative unfortunately.

**Comment by FanMix** [comment]
.NET Core already here ! It's a great port but still .NET Core is not supported, pity...

**Comment by aidanbebbington** [comment]
Would love to support it.  I'm a bit out of touch with the latest .NET these days, so if someone could do a pull request I would be happy to take it.

**Comment by cindro** [comment]
@FanMix for now you can use https://github.com/jarroda/libphonenumber-dotnet (.NET Core is supported)

**Comment by jarroda** [comment]
I will try to take some time to get my fork updated and issue a PR back to this repo.  I had always intended to but got sidetracked with work.

**Comment by twcclegg** [comment]
If any issues with .net core are found, please let me know.
