### ISSUE TITLE
Xamarin Forms Use

### ISSUE THREAD

**Issue by ArranHarbert** [twcclegg/libphonenumber-csharp#61]
Attempting to use this library in a Xamarin Forms mobile application and I'm getting the error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'libphonenumber-csharp 8.9.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any obvious reasons for this, My assumption is that my project needs to be updated to support .net standard 2.0

**Comment by twcclegg** [comment]
I wouldn't think so, the library should support net35, net40, netstandard1.3, netstandard2.0, and everything in between. I don't really have any Xamarin experience unfortunately, not sure what the cause is. If you can point me to a package that does work for you I can look and see if it targets other things I should be able to add it to the next release.

**Comment by AwsomeCode** [comment]
Maybe I can try this thing tomorrow.
https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer

**Comment by ArranHarbert** [comment]
My problem is that we have had to use [this project](https://github.com/erezak/libphonenumber-csharp) because it works, but it hasn't been updated so it has the wrong metadata for some of the countries and its causing problems.

This is a c# portable port of this, so I'm not sure what he is doing differently but it works on that version.

**Comment by ArranHarbert** [comment]
Specifically it doesn't work in portable class libraries (portable45-net45+win8+wp8)

**Comment by twcclegg** [comment]
I've gotten it to work in portable-net45+win 8+wp8+wpa81 locally, let me know if that works for people. I don't know what if anything it will take to get it to build in appveyor, but if things go smoothly I should be able to include that in the next release.

**Comment by OKameric** [comment]
Confirming that this lib is not compatible with PCL

**Comment by ArranHarbert** [comment]
@twcclegg When do you imagine the next release will be, would it be possible for me to have that local copy so I can push it to the testers to test the library's compatibility with our project.

**Comment by twcclegg** [comment]
I was hoping to get it out with yesterday's release but was having some trouble getting it to build in AppVeyor. The releases are about every two weeks, they are released in step with when Google does a new release. In the meantime please let me know if https://ci.appveyor.com/project/twcclegg/libphonenumber-csharp/build/8.9.6-12d17b6/artifacts works for you. If so it'll be included in future releases.

**Comment by OKameric** [comment]
Confirming that https://ci.appveyor.com/project/twcclegg/libphonenumber-csharp/build/8.9.6-12d17b6/artifacts works with PCL targeting portable-net45+wp80+win8+wpa81

**Comment by twcclegg** [comment]
Given the seemingly high interest for this, if there is enough demand I could make a 8.9.6.5 release if people don't want to wait for 8.9.7

**Comment by ArranHarbert** [comment]
I could do with it if it isn't too much effort on your part, if so then just wait until the next release, appreciate the fix as well mate thank you.

**Comment by twcclegg** [comment]
Resolved in version 8.9.7

**Comment by twcclegg** [comment]
I don't suppose anyone knows how to read a file / create a StreamReader from a file in `portable-net45+wp80+win8+wpa81`? It's blocking further porting of the library.

**Comment by OKameric** [comment]
I am not experienced in writing libraries to access filesystem from PCL but  this maybe could help with the issue:
[https://github.com/dsplaisted/PCLStorage](url)
It's a bit outdated though.
When trying to save/load file from the desired platform (android, ios, windows)  I personally use dependency service.
