### ISSUE TITLE
Assembly is not strongly-named

### ISSUE THREAD

**Issue by godspeed22** [twcclegg/libphonenumber-csharp#68]
Is there a reason why the nuget package is not strongly named ?
And is there a solution for this ?

**Comment by twcclegg** [comment]
See https://github.com/twcclegg/libphonenumber-csharp/issues/18 and https://github.com/octokit/octokit.net/issues/405
I do however have plans to sign the package https://blog.nuget.org/20180522/Introducing-signed-package-submissions.html though I'm still looking into how to get a CA cert without being a legal organization.
