### ISSUE TITLE
IsValidNumber return false for valid Solomon Islands phone numbers

### ISSUE THREAD

**Issue by yqset** [twcclegg/libphonenumber-csharp#69]
Example of a Solomon island number:
+677 (71) 52398

I'm using 8.9.10 net40

Happy to provide whatever you need!

**Comment by twcclegg** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=%2B6777152398 shows the same. Please see https://github.com/twcclegg/libphonenumber-csharp/blob/master/CONTRIBUTING.md Google is pretty good at updating their metadata supplied sufficient details.
