### ISSUE TITLE
Enable backspace option in AsYouTypeFormatter

### ISSUE THREAD

**Issue by blerb** [twcclegg/libphonenumber-csharp#70]
Hi, I am using your library in one of our project with Xamarin.iOS.

We are using AsYouTypeFormatter with our textfields.

But I did not found a way to remove last character from AsYouTypeFormatter.

We have backspace option in keyboard to delete last character but i did not find a way to delete character with this formatter.

Need help.

**Comment by twcclegg** [comment]
Similar to your other question, you would have to take it up with Google or come up with some other with around, such as saving the previous return values.
