### ISSUE TITLE
No way to add existing number to update in AsYouTypeFormatter

### ISSUE THREAD

**Issue by blerb** [twcclegg/libphonenumber-csharp#71]
I am having number to udpate that i can not use with AsYouTypeFormtter.

Consider Case:

I am having phoneNumber that is half written 45454 and i am changing coutry code for this number than its format also should get changed.

but I can not load character array to AsYouTypeFormtter. So as to update country region in formatter, formatter needs to be constructed again and it start again from first character.

It should have a way to load character array or complete string to TypeFormatter and continue next char from there.

**Comment by twcclegg** [comment]
This library only intends to port functionality that exists in the upstream Google Java version. In the case of the formatter https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java, only adding individual characters is supported. You could open an issue with them https://groups.google.com/forum/#!forum/libphonenumber-discuss or http://issuetracker.google.com/issues/new?component=192347 alternately you could call Clear on the formatter when the country code changes and then iterate through the current set of digits.
