### ISSUE TITLE
Parsing numbers with leading zeros

### ISSUE THREAD

**Issue by orihomie** [twcclegg/libphonenumber-csharp#72]
Hi, I've tried to use this lib, but, accidently met some problems with some numbers (RU region),
for example, number like '7 016 1610088' or '7 001 1610088'

**First** of my thoughts was because of your inner formats, in which this parts are stored (string would be greatest solution to keep at least national number part), but we have what we have, so let's go on and

**Second**, is that with numbers like that NDC returned as 0 because of this function:
GetLengthOfNationalDestinationCode - internal realization has its _array_ variable, which in this cases is
about length of 2 elements, and code inside written like 

if (array.Length <= 3)
{
    return 0;
}

It's all rooted deep inside of all code of lib, but, may you give me some thoughts about how to solve that problem?

**Comment by twcclegg** [comment]
I'm not sure I fully understand your issue, are you able to try out the numbers using http://libphonenumber.appspot.com? +70161610088 and +70011610088 show up as invalid

**Comment by orihomie** [comment]
Hi, @twcclegg.
They got parsed fine (or it only seems for me) with options: 
defaultCountry entered: RU
Language entered: ru-RU

Still, my issue is what that numbers with leading zeros are parsed into long without them (its nature into parsing any string with leading zeros into long):

long.Parse("001") -> 1

 so 'GetLengthOfNationalDestinationCode' function returns wrong value of national destination code length (it's 0), because the array inside has it's value (for example) {"7", "16160088"}

I'd like to parse out national destionation code and subscriber number out of national number without any other hacks.

**Comment by twcclegg** [comment]
Can you send me a link like http://libphonenumber.appspot.com/phonenumberparser?number=%2B74011610088 that shows the number(s) in question in E.164 format that shows it as possible and valid along with AsYouTypeFormatter results? https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia#List_of_area_codes_in_Russia says all area codes starting with a 0 expired in 2006.

**Comment by orihomie** [comment]
[70161610088 parse result](http://libphonenumber.appspot.com/phonenumberparser?number=70161610088&country=RU&geocodingLocale=ru-RU)
[70061610088 parse result](http://libphonenumber.appspot.com/phonenumberparser?number=70061610088&country=RU&geocodingLocale=ru-RU)

Despite that they are all expired - we're able to use them inside of our infrastructure (I'm working in one of Russia's telecom company), so numbers like this are still in db's.

**Comment by twcclegg** [comment]
Yes, as it shows, both have `isValidNumber` as `flase`, and otherwise `invalid`. You would have to file an issue with [Google](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md). They maintain what is valid.

**Comment by orihomie** [comment]
1

**Comment by orihomie** [comment]
I'm clearing my subscriptions for now and as I remember as we spoke last time - author said number format with leading zeros is invalid and I've agreed with him for a while... until I've got a call from a number with leading zero.
So, this is not about Google and their decisions, this is about usability that provides some kind of comfort to work with.
That's all my thoughts, bye.
