### ISSUE TITLE
Number with leading zeros

### ISSUE THREAD

**Issue by helgesson** [twcclegg/libphonenumber-csharp#77]
When I have a number starting with 0046 the phonenumber util does not recognize this number as a vaild swedish number. Instead of + before nationalcode there is 00
Exampel
"0046081231234"

**Comment by twcclegg** [comment]
This port intends to match the features and behavior of the Google java version. Only E.164 formatted number parse without region code supplied.
Please let me know if you see any behavior that differs from http://libphonenumber.appspot.com/
```c#
            Assert.Equal(phoneUtil.Parse("0046081231234", "SE"), phoneUtil.Parse("+46081231234", null));
            Assert.Throws<NumberParseException>(() => phoneUtil.Parse("0046081231234", null));
```
