### ISSUE TITLE
Region information is not updated

### ISSUE THREAD

**Issue by NLDoron** [twcclegg/libphonenumber-csharp#81]
It seems the region information (in libphonenumber-csharp-master\csharp\PhoneNumbers\res) is not updated- and we should take those region files from the Java version.
The C# version of libphonenumber has regional information about 87 countries, while the Java version has information about 130 countries. 
Additionally, the C# region files are older than the Java region files, so it possible to find differences in region files who exists in both versions.

**Comment by twcclegg** [comment]
That is a work in progress https://github.com/twcclegg/libphonenumber-csharp/pull/45, I'm not sure how the java version worked 6 years ago when this was last updated but currently it reads binary geocoder data, which is generated, I assume at build time, from https://github.com/googlei18n/libphonenumber/tree/master/resources/geocoding.

**Comment by twcclegg** [comment]
Fixed to use resources/
