### ISSUE TITLE
IsNumberMatch very slow

### ISSUE THREAD

**Issue by nbsoftware** [twcclegg/libphonenumber-csharp#85]
I'm trying to match `x` telephone numbers across the whole address book (which can contain `y` contacts and `z` telephone numbers - i.e. multiple phones per contact).

See #84 for code excerpt (even though this issue is about getting an exception on an iOS device which is something quite different than the question I'm asking here).

Issuing multiple calls to IsNumberMatch is super slow.
Possibly because new Regex objects have to be created each time.

It wonder if it would be (a lot?) faster if we had at least a method that would take a collection of strings to match as in
```csharp
public MatchType IsNumberMatch(IList<string> firstNumbers, string secondNumber)
```

I know your library is a 1 to 1 mapping from the original one from Google so I guess it is unlikely you would like to add this to it until Google does so eventually.

So before cloning your repo and trying to add some custom code, I wanted to know if you think this is feasible and if it would help speed up things by not re-creating multiple objects... as in https://stackoverflow.com/questions/39470506/c-sharp-regex-performance-very-slow for instance.

**Comment by nbsoftware** [comment]
But then I realise that it is probably more complicated than just that because passing in only a list of strings would be useless without a correlated id of some kind and so we might need to pass a more complex object as the first parameter.

So back to square one: method is super slow.

Is there any possible optimizations that can be done?

Do you have any idea of how it compares to the original lib, performance-wise?

**Comment by twcclegg** [comment]
I don't believe IsNumberMatch uses regex at all if the PhoneNumber version is used. String version has to call `Parse` which does involve detailed regexes to determine validity and possibility.  

For best performance you should be using 
```C#
public MatchType IsNumberMatch(string firstNumber, string secondNumber)
```
but rather
```c#
public MatchType IsNumberMatch(PhoneNumber firstNumber, PhoneNumber secondNumber)
```

Can you try having all your numbers already parsed before running the batch matching?

**Comment by twcclegg** [comment]
Using the `string` version to do a million calls, half being matches, it took 17.58 seconds whereas the `PhoneNumber` version took 0.64 seconds.

**Comment by nbsoftware** [comment]
Yes, you are probably right, it is most likely `PhoneNumberUtil.Parse` that calls Regexes and is slow.

To answer your question, the first numbers come from the user's address book and come as strings, the second numbers come from a database and also come as strings.

So yes, I could Parse them beforehand, but I suppose it would basically take ages doing so number by by number. Even if doing so will definitively save compared to doing it for each matching attempt.

I'll do some tests in that direction, but I'm afraid it'll only shift the issue to the `Parse` method.

In your second test, how long did it take to Parse all the strings and return a PhoneNumber object?

**Comment by twcclegg** [comment]
I haven't benchmarked `Parse` as compared to the Java version but it's at mercy of the speed of the regexs. Your issue is https://github.com/twcclegg/libphonenumber-csharp/blob/master/csharp/PhoneNumbers/InternalRegexOptions.cs due to
`Error	CS0117	'RegexOptions' does not contain a definition for 'Compiled'	PhoneNumbers(portable-net45+win8+wpa81+wp8)`

**Comment by twcclegg** [comment]
In your example from #84 if you Parse `phoneNumber` first (if you aren't already) it should cut your time in half.

**Comment by nbsoftware** [comment]
Agreed. And `RegexOptions.Compiled` is not available in iOS for instance because the platform does not support `Reflection.Emit`. It's a pity.

On other platforms, does the source code really benefit from `RegexOptions.Compiled` placing results of `new Regex(...)` in static variables to be reused from subsequent calls to `Parse`?

**Comment by twcclegg** [comment]
All regexs save one are are static readonly, a million parses takes about 5.6 seconds in netstandard2.0 on OSX. The first parse does take ~50ms, see #4, which I've been slowly working on resolving.

**Comment by nbsoftware** [comment]
In the end I did parse the numbers beforehand (and in the background) which does accelerate the subsequent matching tentatives.

I'll see how it goes from there.

Thanks
