### ISSUE TITLE
GetExampleNumber is returning null

### ISSUE THREAD

**Issue by adrianknight89** [twcclegg/libphonenumber-csharp#86]
I'm trying to get valid example numbers based on region code, but I keep getting null.

```
var phoneNumberUtil = PhoneNumberUtil.GetInstance();

phoneNumberUtil.GetExampleNumber("1");
```

I tried passing `+` also, but that didn't work either.

`phoneNumberUtil.GetExampleNumber("+1");`

**Comment by twcclegg** [comment]
1 is the country code for NANPA, this is looking or region code such as US, CA, GB, etc.
