### ISSUE TITLE
ArgumentException when initializing AsYouTypeFormatter in net35

### ISSUE THREAD

**Issue by MichaelEdk** [twcclegg/libphonenumber-csharp#87]
Because the implementation of SortedSet.Add in the compat folder does not check for the existence of the key in the underlying dictionary, an ArgumentException is thrown. The following code snippet takes about 20 secs to execute:

`var text = "02108128206";
var asYouTypeFormatter = new AsYouTypeFormatter("NZ");`

Adding a guard clause inside Add(T item) along the lines of this seems to fix the issue:

`if (items.ContainsKey(item))
 {
    return false;
 }`

**Comment by twcclegg** [comment]
Merged, I didn't add net35 support but surprising bottleneck. Thanks!
