### ISSUE TITLE
Metadata 7.4.1

### ISSUE THREAD

**Issue by StephaneG31** [twcclegg/libphonenumber-csharp#9]
Please update metadata from 7.0.11 to 7.4.1 (https://github.com/googlei18n/libphonenumber/commit/ada9fd4c05e72f63899eefe42335f6efdb0360bc)

**Comment by MishoAbS** [comment]
can you please update the Metadata again, many Prefix has been added and the library is still returning invalid phone number while its valid on Java/Javascript.
Thanks

**Comment by jzelos** [comment]
We use this and just notice the Brazilian numbering plan is out of date with the 9 prefix being applied to additional regions. Presumably anyone could update the metadata? Will that also update the nuget package automatically or do the owners have to push that? (apologies if that's obviously yes or no, don't use github much)

**Comment by jzelos** [comment]
Have updated the meta data and created a pull request.

**Comment by aidanbebbington** [comment]
Thanks! And sorry for my tardiness.  It's up on nuget.com now.
