### ISSUE TITLE
iOS build issue

### ISSUE THREAD

**Issue by jeffries7** [twcclegg/libphonenumber-csharp#90]
I seem to be getting an issue on iOS that when this is included in my project the build never completes. It doesn't fail, just never finished. I've checked the logs and can't see any issues there, works fine on Android.

**Comment by twcclegg** [comment]
iOS seems to work for others (albeit slow due to lack of compiled regexs) not sure how to assist without more information, have you tried building with higher verbosity logging?

**Comment by jeffries7** [comment]
I'm building out of Unity, is there anything extra that I need to do in Xcode?
I'll try building with higher verbosity.
