### ISSUE TITLE
Vietnamese Phone Numbers Not Returning as Valid

### ISSUE THREAD

**Issue by volearix** [twcclegg/libphonenumber-csharp#91]
Vietnam has switched all their 11-digit mobile numbers to 10 digits as of 15th September 2018. The network operators allowed subscribers to continue using their old 11-digit number until 14th November 2018. It looks like google already fixed this in 8.10.1, any chance of getting this data updated soon? See below.

Nov 21, 2018: v8.10.1
Metadata changes:
 - Updated phone metadata for region code(s):
   AE, AL, AT, AX, BW, BY, CC, CL, CN, CX, DE, FI, FR, GB, GG, HN, IM, IN, IR,
   JE, LA, LI, LT, MM, MN, MY, NZ, PK, SE, SK, SM, UZ, **VN**, ZM, ZW
 - Updated short number metadata for region code(s):
   AT, AX, BY, CF, CL, DE, ER, FI, FM, FR, GA, IN, IR, LI, LT, MM, MN, MY, NE,
   NZ, OM, PK, SE, SM, UZ, ZA, ZM, ZW
 - Updated geocoding data for country calling code(s):
   33 (en), 43 (de, en), 49 (en), 52 (en), 60 (en), 64 (en), 91 (en), 263 (en),
   358 (en, sv), 370 (en)
 - Updated carrier data for country calling code(s):
   44 (en), 56 (en), 60 (en), 64 (en), **84 (en)**, 91 (en), 92 (en), 95 (en),
   98 (en, fa), 260 (en), 267 (en), 358 (en), 370 (en), 423 (en), 976 (en),
   998 (en)
 - Updated / refreshed time zone meta data.

**Comment by twcclegg** [comment]
Yes, there has been some delay in releases 8.10.x due to porting issue with https://github.com/googlei18n/libphonenumber/releases/tag/v8.10.0, hopefully I'm able to get to the bottom of that soon, otherwise I can release a 8.9.18 as a stop gap.

**Comment by twcclegg** [comment]
8.10.1 released.
