### ISSUE TITLE
Is Timezone information supported?

### ISSUE THREAD

**Issue by sseyalioglu** [twcclegg/libphonenumber-csharp#93]
Seems like java version has the timezone details for the country/region but could not find the same in c# version.

Is there a plan to have this included?

**Comment by twcclegg** [comment]
There are plans for it and it is partially done in https://github.com/twcclegg/libphonenumber-csharp/pull/45. I have yet to find the time to get back to that, it needs to get split up into a series of smaller PRs.

**Comment by erik1988** [comment]
It would be wonderful to have the timezone feature. Thanks for all your hard work.

**Comment by twcclegg** [comment]
I will need to test to confirm but it seems like this may be resolved with #163
