### ISSUE TITLE
Manila phone numbers extending to 8 digits

### ISSUE THREAD

**Issue by dmumladze** [twcclegg/libphonenumber-csharp#94]
Metro Manila and neighboring areas are [getting an extra digit](https://www.rappler.com/business/219230-pldt-globe-subscribers-telephone-numbers-march-2019) on their telephone numbers, and users of our system have started updating existing 7 digit phone number to new 8 digit numbers. We have to disable phone number validations temporarily (during certain periods of the day), and that has affected the overall quality of data, which makes certain investors nervous. Please let me know when you plan to accommodate this global change..

Thanks and regards.

**Comment by twcclegg** [comment]
This library uses the phone number metadata from https://github.com/googlei18n/libphonenumber/, updated almost always within 24 hours of when they put out a release. Please see https://issuetracker.google.com/issues/122924177.

**Comment by dmumladze** [comment]
It seems the maintainers will have this ready by the March 19 deadline. Thanks.
