### ISSUE TITLE
System.IO.FileNotFoundException when referenced from an AWS Lambda project

### ISSUE THREAD

**Issue by rianjs** [twcclegg/libphonenumber-csharp#95]
I'm not sure if this is a libphonenumber issue, or an AWS Lambda test tool issue.

Repro steps:
0) Install the AWS Lambda test tool package: https://aws.amazon.com/blogs/developer/debugging-net-core-aws-lambda-functions-using-the-aws-net-mock-lambda-test-tool/
1) Create an empty Serverless Lambda app
2) Add the libphonenumber package as a dependency
3) In the `Function` constructor, do `var foo = PhoneNumberUtil.GetInstance();`
4) Run the debugger
5) Send any request

The constructor doesn't run at all.

```
System.IO.FileNotFoundException: Could not load file or assembly 'PhoneNumbers, Version=8.10.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at Mercury.Function..ctor()
```

The smallest repro case I could come up with attached here.
[AWSServerlessApp.zip](https://github.com/twcclegg/libphonenumber-csharp/files/2972689/AWSServerlessApp.zip)

**Comment by rianjs** [comment]
I have also downloaded the source code for libphonenumber, and added that csproj as a project reference in a lambda solution. It builds fine, but as soon as I invoke the lambda via the test tool, the same error occurs.

I have opened a bug in the lambda test tool project as well, as I'm not sure which side the problem is on:
https://github.com/aws/aws-lambda-dotnet/issues/419

**Comment by twcclegg** [comment]
Quite the unusual error, I can see if I have some time to take a look. I haven't had any issue using the library within AWS.

**Comment by rianjs** [comment]
It has the feel of a bug in the Lambda test tool. I wouldn't be surprised if it works in a real Lambda environment. It certainly works in .NET Core applications (web and console).

You do have to disable "Just my code" to hit a breakpoint, and the stack trace is in the Lambda test tool code. Decompiling the test tool assembly, it doesn't look like it's doing anything _too_ weird where the exception is thrown. But the fact that it's using reflection `S.A.R.LoadAssembly`, IIRC) to load Lambda assemblies and having the library fall down _could_ indicate a problem in the library itself. (And other nuget dependencies work fine.)

I also downloaded the source, and added it as a project reference. Same error when running locally, so I don't think nuget assembly references are the issue.

**Comment by rianjs** [comment]
This [ended up being a bug in the Lambda test tool](https://github.com/aws/aws-lambda-dotnet/issues/419). Closing.
