### ISSUE TITLE
PhoneNumberOfflineGeocoder not threadsafe

### ISSUE THREAD

**Issue by auky-au** [twcclegg/libphonenumber-csharp#96]
Hi, we have the following unit tests which fails.
Test1 fails when we run all our tests, we're getting a NullReferenceException. But just running the single test will succeed. So we've fixed it by catching the exception and retry getting the description. Sorry, don't have enough time to rewrite all our test to post it here... But i think if you've fixed Test2, Test1 will be fixed too.

Test2 throws an InvalidOperationException. We did the same fix...

`        [Theory]
        [InlineData("+31103004205", "NL")]
        [InlineData("+3250660640", "BE")]
        [InlineData("+31103004201", "NL")]
        [InlineData("+3250660641", "BE")]
        [InlineData("+31103004202", "NL")]
        [InlineData("+3250660642", "BE")]
        [InlineData("+31103004203", "NL")]
        [InlineData("+3250660643", "BE")]
        [InlineData("+31103004204", "NL")]
        [InlineData("+3250660644", "BE")]
        public void Test1(string number, string region)
        {
            var phoneUtil = PhoneNumberUtil.GetInstance();
            var phoneNumber = phoneUtil.Parse(number, region); ;

            var areaName = GetAreaName(phoneNumber);
            Assert.NotEmpty(areaName);
        }

        [Fact]
        public void Test2()
        {
            var index = 0;

            var result = Parallel.ForEach(Enumerable.Repeat("0103004205", 10000),
                (x) =>
                {
                    index++;
                    var phoneUtil = PhoneNumberUtil.GetInstance();
                    var phoneNumber = phoneUtil.Parse(x, "NL"); ;
                    var areaName = GetAreaName(phoneNumber);
                    Assert.Equal("Rotterdam", areaName);
                });
        }

        public string GetAreaName(PhoneNumber number)
        {
            var geocoder = PhoneNumberOfflineGeocoder.GetInstance();

            try
            {
                return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch (InvalidOperationException)
            {
                //return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch (NullReferenceException)
            {
                //return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch
            {
            }
            return string.Empty;
        }`

And if i Load the datafile before i get the description, it will also be fixed...
`        [Theory]
        [InlineData("+31103004205", "NL", 31)]
        [InlineData("+3250660640", "BE", 32)]
        [InlineData("+31103004201", "NL", 31)]
        [InlineData("+3250660641", "BE", 32)]
        [InlineData("+31103004202", "NL", 31)]
        [InlineData("+3250660642", "BE", 32)]
        [InlineData("+31103004203", "NL", 31)]
        [InlineData("+3250660643", "BE", 32)]
        [InlineData("+31103004204", "NL", 31)]
        [InlineData("+3250660644", "BE", 32)]
        public void Test1(string number, string region, int countryCode)
        {
            var phoneUtil = PhoneNumberUtil.GetInstance();
            var phoneNumber = phoneUtil.Parse(number, region); ;

            var areaName = GetAreaName(phoneNumber, countryCode);
            Assert.NotEmpty(areaName);
        }

        [Fact]
        public void Test2()
        {
            var index = 0;

            var result = Parallel.ForEach(Enumerable.Repeat("0103004205", 10000),
                (x) =>
                {
                    index++;
                    var phoneUtil = PhoneNumberUtil.GetInstance();
                    var phoneNumber = phoneUtil.Parse(x, "NL"); ;
                    var areaName = GetAreaName(phoneNumber, 31);
                    Assert.Equal("Rotterdam", areaName);
                });
        }

        public string GetAreaName(PhoneNumber number, int countryCode)
        {
            var geocoder = PhoneNumberOfflineGeocoder.GetInstance();

            try
            {
                geocoder.LoadDataFile(Locale.English, countryCode);
                return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch (InvalidOperationException)
            {
                //return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch (NullReferenceException)
            {
                //return geocoder.GetDescriptionForNumber(number, Locale.English)?.Replace("'", "''");
            }
            catch
            {
            }
            return string.Empty;
        }`

**Comment by twcclegg** [comment]
Interesting, I spent some time working on reproducing / debugging. I don't have a great setup to test this on the java version at the moment but it would be interesting to see the behavior there. I don't know if is by design that there is what appears to be overlapping metadata.

**Comment by twcclegg** [comment]
As an aside you don't want to call PhoneNumberUtil's or PhoneNumberOfflineGeocoder's more than need be since it involves acquiring a lock to get the same instance over and over.
