### ISSUE TITLE
IsValidNumber return false for some Valid Nigerian Numbers 

### ISSUE THREAD

**Issue by Xtremrules** [twcclegg/libphonenumber-csharp#99]
Numbers in Nigeria (NG) with the format `0801 XXX XXXX` is seen as invalid.

I'm using version 8.10.10 netstandard2.0

**Comment by AwsomeCode** [comment]
Hi @Xtremrules 
Please verify at https://libphonenumber.appspot.com/

If an issue exists kindly report at https://github.com/googlei18n/libphonenumber
else you can report it here.

**Comment by Xtremrules** [comment]
Hi @AwsomeCode, After proper investigation, the issue is actually for numbers with format `0801 4XX XXXX` and it's not currently issued by any telecom company. the issue is a false-positive.

Thanks for your quick response.

**Comment by twcclegg** [comment]
Also thanks @AwsomeCode for helping out here!
